import Foundation
import XCTest

final class PlantDetailExperienceTests: XCTestCase {
    func testAddPlantFlowUsesSimpleCatalogFirstSetup() throws {
        let rootURL = repositoryRootURL()
        let addPlantBaseSource = try source("Ohana/Features/Plants/Views/AddPlantView.swift", rootURL: rootURL)
        let addPlantReviewSource = try source("Ohana/Features/Plants/Views/AddPlantView+ReviewSections.swift", rootURL: rootURL)
        let addPlantSource = [addPlantBaseSource, addPlantReviewSource].joined(separator: "\n")
        let addPlantCatalogPickerSource = try source("Ohana/Features/Plants/Views/AddPlantCatalogPickerModel.swift", rootURL: rootURL)
        let controlsSource = try source("Ohana/Shared/Components/OhanaFormControls.swift", rootURL: rootURL)
        let plantUITestSource = try source("OhanaUITests/PlantModuleUITests.swift", rootURL: rootURL)

        XCTAssertTrue(addPlantSource.contains("addPlantSimpleHeader"))
        XCTAssertTrue(addPlantSource.contains("add-plant-simple-header"))
        XCTAssertTrue(addPlantSource.contains("plantSpeciesPickerSection"))
        XCTAssertTrue(addPlantSource.contains("add-plant-species-picker"))
        XCTAssertTrue(addPlantSource.contains("selectedCatalogGroup"))
        XCTAssertTrue(addPlantSource.contains("catalogGroupButton"))
        XCTAssertTrue(addPlantSource.contains("AddPlantCatalogPickerModel.entries(for: selectedCatalogGroup)"))
        XCTAssertTrue(addPlantCatalogPickerSource.contains("enum PlantCatalogBrowsingGroup"))
        XCTAssertTrue(addPlantCatalogPickerSource.contains("case recommended"))
        XCTAssertTrue(addPlantCatalogPickerSource.contains("case foliageVines"))
        XCTAssertTrue(addPlantCatalogPickerSource.contains("case lowLight"))
        XCTAssertTrue(addPlantCatalogPickerSource.contains("case petSafe"))
        XCTAssertTrue(addPlantCatalogPickerSource.contains("case succulentCactus"))
        XCTAssertTrue(addPlantCatalogPickerSource.contains("case floweringBalcony"))
        XCTAssertTrue(addPlantCatalogPickerSource.contains("func includes(_ entry: PlantCatalogEntry) -> Bool"))
        XCTAssertTrue(addPlantCatalogPickerSource.contains("static func entries(for group: PlantCatalogBrowsingGroup)"))
        XCTAssertTrue(addPlantSource.contains("catalogSearchField"))
        XCTAssertTrue(addPlantSource.contains("catalogSearchResultsList"))
        XCTAssertTrue(addPlantSource.contains("PlantCatalog.searchResults(catalogQuery, limit: 8)"))
        XCTAssertTrue(addPlantSource.contains("carePlanPreviewSummary"))
        XCTAssertTrue(addPlantSource.contains("carePlanPreviewDetail"))
        XCTAssertTrue(addPlantSource.contains("nameAndPlaceSection"))
        XCTAssertTrue(addPlantSource.contains("add-plant-name-place"))
        XCTAssertTrue(addPlantSource.contains("plantNameSummarySection"))
        XCTAssertTrue(addPlantSource.contains("add-plant-name-summary"))
        XCTAssertTrue(addPlantSource.contains("add-plant-name-summary-value"))
        XCTAssertTrue(addPlantSource.contains("add-plant-name-edit-action"))
        XCTAssertTrue(addPlantSource.contains("add-plant-name-use-catalog-action"))
        XCTAssertTrue(addPlantSource.contains("inlineFormField"))
        XCTAssertTrue(addPlantSource.contains("previousCatalogName"))
        XCTAssertTrue(addPlantSource.contains("shouldUseCatalogName"))
        XCTAssertTrue(addPlantSource.contains("catalogQuery = \"\""))
        XCTAssertTrue(addPlantSource.contains("name = defaults.name"))
        XCTAssertTrue(addPlantSource.contains("isCustomizingName = false"))
        XCTAssertTrue(addPlantSource.contains("wateringInterval = defaults.wateringIntervalDays"))
        XCTAssertTrue(addPlantSource.contains("fertilizingInterval = defaults.fertilizingIntervalDays"))
        XCTAssertTrue(addPlantSource.contains("showingOptionalPlantDetails"))
        XCTAssertTrue(addPlantSource.contains("showingCustomRoomField"))
        XCTAssertTrue(addPlantSource.contains("showingCustomLocationField"))
        XCTAssertTrue(addPlantSource.contains("usesCustomRoomEntry"))
        XCTAssertTrue(addPlantSource.contains("usesCustomLocationEntry"))
        XCTAssertTrue(addPlantSource.contains("essentialCareSection"))
        XCTAssertTrue(addPlantSource.contains("optionalPlantDetailsSection"))
        XCTAssertTrue(addPlantSource.contains("speciesOverrideSection"))
        XCTAssertTrue(addPlantSource.contains("careAdjustmentSection"))
        XCTAssertTrue(addPlantSource.contains("avatarPickerSection"))
        XCTAssertTrue(addPlantSource.contains("add-plant-essential-care"))
        XCTAssertTrue(addPlantSource.contains("add-plant-optional-details"))
        XCTAssertTrue(addPlantSource.contains("add-plant-optional-details-toggle"))
        XCTAssertTrue(addPlantSource.contains("add-plant-optional-details-content"))
        XCTAssertTrue(addPlantSource.contains("add-plant-species-override"))
        XCTAssertTrue(addPlantSource.contains("add-plant-care-adjustments"))
        XCTAssertTrue(addPlantSource.contains("add-plant-avatar-picker"))
        XCTAssertTrue(addPlantSource.contains("add-plant-common-catalog-\\(entry.id)"))
        XCTAssertTrue(addPlantCatalogPickerSource.contains("enum PlantCatalogQuickFilter"))
        XCTAssertTrue(addPlantCatalogPickerSource.contains("case beginner"))
        XCTAssertTrue(addPlantSource.contains("OhanaChoiceChipRow("))
        XCTAssertTrue(addPlantSource.contains("add-plant-room-choice"))
        XCTAssertTrue(addPlantSource.contains("add-plant-location-choice"))
        XCTAssertTrue(addPlantSource.contains("add-plant-room-custom-toggle"))
        XCTAssertTrue(addPlantSource.contains("add-plant-location-custom-toggle"))
        XCTAssertTrue(addPlantSource.contains("if showingCustomRoomField || usesCustomRoomEntry"))
        XCTAssertTrue(addPlantSource.contains("if showingCustomLocationField || usesCustomLocationEntry"))
        XCTAssertTrue(addPlantSource.contains(".onChange(of: roomName)"))
        XCTAssertTrue(addPlantSource.contains(".onChange(of: location)"))
        XCTAssertTrue(addPlantSource.contains("commonRoomOptions.contains(newValue.trimmingCharacters"))
        XCTAssertTrue(addPlantSource.contains("commonSpotOptions.contains(newValue.trimmingCharacters"))
        XCTAssertTrue(addPlantSource.contains("revealCustomRoomField()"))
        XCTAssertTrue(addPlantSource.contains("revealCustomLocationField()"))
        XCTAssertTrue(addPlantSource.contains("OhanaFrameScheduler.runAfterNextFrame"))
        XCTAssertTrue(addPlantSource.contains("add-plant-pot-material-choice"))
        XCTAssertTrue(addPlantSource.contains("add-plant-soil-choice"))
        XCTAssertTrue(addPlantSource.contains("add-plant-source-choice"))
        XCTAssertTrue(controlsSource.contains("struct OhanaChoiceChipRow"))
        XCTAssertTrue(controlsSource.contains("Keep the bound text open-ended"))
        XCTAssertFalse(addPlantSource.contains("profileSetupOverview"))
        XCTAssertFalse(addPlantSource.contains("add-plant-profile-overview"))
        XCTAssertFalse(addPlantSource.contains("profileReadinessItems"))
        XCTAssertFalse(addPlantSource.contains("profileCompletionPercent"))
        XCTAssertFalse(addPlantSource.contains("commonPlantChoiceSection"))
        XCTAssertFalse(addPlantSource.contains("add-plant-common-plants"))
        XCTAssertFalse(addPlantSource.contains("selectedCatalogFilter"))
        XCTAssertFalse(addPlantSource.contains("catalogQuickFilterButton"))
        XCTAssertFalse(addPlantSource.contains("Optional species match"))
        XCTAssertFalse(addPlantSource.contains("Skip if you are not sure"))
        XCTAssertFalse(addPlantSource.contains("PlantCreationOutcomeItem"))
        XCTAssertFalse(addPlantSource.contains("creationOutcomeItems"))
        XCTAssertFalse(addPlantSource.contains("creationOutcomePreview"))
        XCTAssertFalse(addPlantSource.contains("add-plant-creation-outcome-preview"))
        XCTAssertTrue(addPlantSource.contains("@FocusState private var focusedField: AddPlantFocusField?"))
        XCTAssertTrue(addPlantSource.contains("private enum AddPlantFocusField"))
        XCTAssertTrue(addPlantSource.contains(".scrollDismissesKeyboard(.interactively)"))
        XCTAssertTrue(addPlantSource.contains("keyboardFocusSpacer"))
        XCTAssertTrue(addPlantSource.contains("add-plant-keyboard-done"))
        XCTAssertTrue(addPlantSource.contains(".focused($focusedField, equals: focusField)"))
        XCTAssertTrue(addPlantSource.contains(".onSubmit { focusAfterSubmit(focusField) }"))
        XCTAssertTrue(addPlantSource.contains("focusAfterSubmit(_ field: AddPlantFocusField)"))
        XCTAssertTrue(addPlantSource.contains("case .catalogSearch:\n            focusedField = nil"))
        XCTAssertTrue(addPlantSource.contains("focusedField = .room"))
        XCTAssertTrue(addPlantSource.contains("focusedField = .location"))
        XCTAssertTrue(addPlantSource.contains("add-plant-pot-material-input"))
        XCTAssertTrue(addPlantSource.contains("add-plant-soil-input"))
        XCTAssertTrue(addPlantSource.contains("add-plant-source-input"))
        XCTAssertFalse(addPlantSource.contains("添加植物 🌿"))
        XCTAssertFalse(addPlantSource.contains("Add plant 🌿"))
        XCTAssertFalse(addPlantSource.contains("Pflanze hinzufügen 🌿"))
        XCTAssertTrue(plantUITestSource.contains("let plantName = addPlantFromHomePlantsTab(in: app)"))
        XCTAssertTrue(plantUITestSource.contains("let expectedPlantName = \"pothos\""))
        XCTAssertTrue(plantUITestSource.contains("testAddPlantPrimaryPathUsesCatalogAndChoiceChipsWithoutTyping"))
        XCTAssertTrue(plantUITestSource.contains("assertAddPlantPrimaryPathKeepsCustomTextFieldsHidden"))
        XCTAssertTrue(plantUITestSource.contains("app.textFields[\"add-plant-name-input\"].exists"))
        XCTAssertTrue(plantUITestSource.contains("app.textFields[\"add-plant-room-input\"].exists"))
        XCTAssertTrue(plantUITestSource.contains("app.textFields[\"add-plant-location-input\"].exists"))
        XCTAssertTrue(plantUITestSource.contains("add-plant-optional-details-content"))
        XCTAssertFalse(plantUITestSource.contains("typeText(plantName, intoTextField: \"add-plant-name-input\""))
    }

    func testHomePlantWalletQuickActionsAreActionable() throws {
        let rootURL = repositoryRootURL()
        let componentsSource = try source("Ohana/Features/Home/Views/VerticalSolidHomeComponents.swift", rootURL: rootURL)
        let homeQuickActionsSource = try source("Ohana/Features/Home/Views/VerticalSolidHomeView+QuickActions.swift", rootURL: rootURL)
        let routeSource = try source("Ohana/Features/Home/HomeRouteCoordinator.swift", rootURL: rootURL)
        let sheetSource = try source("Ohana/Features/Home/FocusHomeRouteSheetModifier.swift", rootURL: rootURL)
        let containerSource = try source("Ohana/Features/Home/HomePlantCareLogRouteContainer.swift", rootURL: rootURL)

        XCTAssertTrue(componentsSource.contains("actionType: \"plantWater\""))
        XCTAssertTrue(componentsSource.contains("actionType: \"fertilizePlant\""))
        XCTAssertTrue(componentsSource.contains("actionType: \"plantNote\""))
        XCTAssertTrue(componentsSource.contains("actionType: \"plantDetail\""))
        XCTAssertTrue(componentsSource.contains("performPlantAction(.water, card: card)"))
        XCTAssertTrue(componentsSource.contains("performPlantAction(.fertilize, card: card)"))
        XCTAssertTrue(componentsSource.contains("performPlantAction(.log, card: card)"))
        XCTAssertTrue(componentsSource.contains("performPlantAction(.detail, card: card)"))
        XCTAssertTrue(homeQuickActionsSource.contains("recordPlantQuickCare(.watering"))
        XCTAssertTrue(homeQuickActionsSource.contains("recordPlantQuickCare(.fertilizing"))
        XCTAssertTrue(homeQuickActionsSource.contains("routeCoordinator.openSheet(.plantCareLog"))
        XCTAssertTrue(homeQuickActionsSource.contains("commandExecutor.recordPlantCare("))
        XCTAssertTrue(routeSource.contains("case plantCareLog(UUID, initialCareType: PlantCareType)"))
        XCTAssertTrue(sheetSource.contains("HomePlantCareLogRouteContainer("))
        XCTAssertTrue(containerSource.contains("PlantCareLogSheet("))
        XCTAssertTrue(containerSource.contains("HomeCommandExecutor(modelContext: modelContext, services: appServices).recordPlantCare("))
    }

    func testPlantCareTypeCopyUsesViewLanguageAcrossHighTrafficSurfaces() throws {
        let rootURL = repositoryRootURL()
        let modelSource = try source("Ohana/Models/PlantCareLog.swift", rootURL: rootURL)
        let focusCardSource = try source("Ohana/Features/Plants/PlantFocusCardAdapter.swift", rootURL: rootURL)
        let dashboardSource = try source("Ohana/Features/Plants/Views/PlantDashboardView.swift", rootURL: rootURL)
        let dashboardWalletSource = try source("Ohana/Features/Plants/Views/PlantDashboardView+WalletDeck.swift", rootURL: rootURL)
        let dashboardSectionsSource = try source("Ohana/Features/Plants/Views/PlantDashboardView+Sections.swift", rootURL: rootURL)
        let carePlanSheetSource = try source("Ohana/Features/Plants/Views/PlantDashboardCarePlanSheet.swift", rootURL: rootURL)
        let siteDetailSource = try source("Ohana/Features/Plants/Views/PlantSiteDetailSheet.swift", rootURL: rootURL)
        let detailSource = try source("Ohana/Features/Plants/Views/PlantDetailView.swift", rootURL: rootURL)
        let detailActionsSource = try source("Ohana/Features/Plants/Views/PlantDetailView+Actions.swift", rootURL: rootURL)
        let detailCareSource = try source("Ohana/Features/Plants/Views/PlantDetailView+CareSections.swift", rootURL: rootURL)
        let detailHealthSource = try source("Ohana/Features/Plants/Views/PlantDetailView+HealthGrowthSections.swift", rootURL: rootURL)
        let detailTimelineSource = try source("Ohana/Features/Plants/Views/PlantDetailView+HeroTimelineDelete.swift", rootURL: rootURL)
        let careLogSheetSource = try source("Ohana/Features/Plants/Views/PlantCareLogSheet.swift", rootURL: rootURL)
        let commandSource = try source("Ohana/Features/Plants/PlantCommands.swift", rootURL: rootURL)
        let carePlanServiceSource = try source("Ohana/Features/Plants/PlantCarePlanService.swift", rootURL: rootURL)
        let scheduleServiceSource = try source("Ohana/Domain/Services/PlantCarePlanScheduleService.swift", rootURL: rootURL)
        let exportServiceSource = try source("Ohana/Features/Plants/PlantGrowthDiaryExportService.swift", rootURL: rootURL)

        XCTAssertTrue(modelSource.contains("func displayName(l: L10n) -> String"))
        XCTAssertTrue(focusCardSource.contains("$0.careType.displayName(l: l).uppercased()"))
        XCTAssertTrue(dashboardSource.contains("log.careType.displayName(l: l)"))
        XCTAssertTrue(dashboardSource.contains("nextTask.careType.displayName(l: l)"))
        XCTAssertTrue(dashboardWalletSource.contains("nextTask.careType.displayName(l: l)"))
        XCTAssertTrue(dashboardWalletSource.contains("let careTypeName = nextTask.careType.displayName(l: l)"))
        XCTAssertTrue(dashboardSectionsSource.contains("let careTypeName = task.careType.displayName(l: l)"))
        XCTAssertTrue(carePlanSheetSource.contains("let careTypeName = task.careType.displayName(l: l)"))
        XCTAssertTrue(siteDetailSource.contains("let careTypeName = task.careType.displayName(l: l)"))
        XCTAssertTrue(detailSource.contains("latestHealthReviewLog.careType.displayName(l: l)"))
        XCTAssertTrue(detailSource.contains("log.careType.displayName(l: l)"))
        XCTAssertTrue(detailActionsSource.contains("type.displayName(l: l)"))
        XCTAssertTrue(detailCareSource.contains("PlantCareType.pestCheck.displayName(l: l)"))
        XCTAssertTrue(detailCareSource.contains("type.displayName(l: l)"))
        XCTAssertTrue(detailHealthSource.contains("PlantCareType.yellowLeaf.displayName(l: l)"))
        XCTAssertTrue(detailTimelineSource.contains("latest.careType.displayName(l: l)"))
        XCTAssertTrue(detailTimelineSource.contains("log.careType.displayName(l: l)"))
        XCTAssertTrue(careLogSheetSource.contains("selectedCareType.displayName(l: l)"))
        XCTAssertTrue(careLogSheetSource.contains("type.displayName(l: l)"))
        XCTAssertTrue(commandSource.contains("let careTypeName = type.displayName(l: l)"))
        XCTAssertTrue(carePlanServiceSource.contains("type.displayName(l: l)"))
        XCTAssertTrue(scheduleServiceSource.contains("task.careType.displayName(l: l)"))
        XCTAssertTrue(exportServiceSource.contains("log.careType.displayName(l: l)"))
    }

    func testPlantDashboardReadsLikeCareHubInsteadOfIconGrid() throws {
        let rootURL = repositoryRootURL()
        let dashboardBaseSource = try source("Ohana/Features/Plants/Views/PlantDashboardView.swift", rootURL: rootURL)
        let dashboardSectionsSource = try source("Ohana/Features/Plants/Views/PlantDashboardView+Sections.swift", rootURL: rootURL)
        let dashboardDiscoverySource = try source("Ohana/Features/Plants/Views/PlantDashboardView+DiscoverySections.swift", rootURL: rootURL)
        let dashboardWalletSource = try source("Ohana/Features/Plants/Views/PlantDashboardView+WalletDeck.swift", rootURL: rootURL)
        let dashboardRoomRailSource = try source("Ohana/Features/Plants/Views/PlantDashboardView+RoomRail.swift", rootURL: rootURL)
        let plantUITestSource = try source("OhanaUITests/PlantModuleUITests.swift", rootURL: rootURL)
        let settingsDebugSource = try source("Ohana/Features/Settings/Views/SettingsView+Debug.swift", rootURL: rootURL)
        let dashboardSource = [
            dashboardBaseSource,
            dashboardSectionsSource,
            dashboardDiscoverySource,
            dashboardWalletSource,
            dashboardRoomRailSource
        ].joined(separator: "\n")

        XCTAssertTrue(dashboardSource.contains("enum PlantDashboardEntryMode"))
        XCTAssertTrue(dashboardSource.contains("initialMode: PlantDashboardEntryMode = .sites"))
        XCTAssertTrue(dashboardSource.contains("PlantDashboardMode(entryMode: initialMode)"))
        XCTAssertTrue(dashboardSource.contains("dashboardOverviewCard"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-overview"))
        XCTAssertTrue(dashboardSource.contains("dashboardLibraryAvatar"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-library-avatar"))
        XCTAssertTrue(dashboardSource.contains("dashboardActionCapsule"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-action-capsule"))
        XCTAssertTrue(dashboardSource.contains("dashboardStatusRibbon"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-status-ribbon"))
        XCTAssertTrue(dashboardSource.contains("dashboardStatusChip"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-status-chip-\\(id)"))
        XCTAssertTrue(dashboardSource.contains("dashboardQuickActionRail"))
        XCTAssertTrue(dashboardSource.contains("dashboardQuickActionButton"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-quick-actions"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-quick-action-\\(id)"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-open-filters"))
        XCTAssertTrue(dashboardSource.contains("openDashboardFilters()"))
        XCTAssertTrue(dashboardSource.contains("openDashboardCarePlan()"))
        XCTAssertTrue(dashboardSource.contains("openDashboardProfileQueue()"))
        XCTAssertTrue(dashboardSource.contains("openDashboardPhotos()"))
        XCTAssertTrue(dashboardSource.contains("PlantDashboardMode"))
        XCTAssertTrue(dashboardSource.contains("case photos"))
        XCTAssertTrue(dashboardSource.contains("primaryCases"))
        XCTAssertTrue(dashboardSource.contains("PlantDashboardMode.primaryCases"))
        XCTAssertTrue(dashboardSource.contains("selectedDashboardMode: PlantDashboardMode = .sites"))
        XCTAssertTrue(dashboardSource.contains("dashboardModePicker"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-mode-picker"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-mode-\\(mode.rawValue)"))
        XCTAssertTrue(dashboardSource.contains("case .sites: l.tr(zh: \"位置\""))
        XCTAssertTrue(dashboardSource.contains("case .plants: l.tr(zh: \"植物\""))
        XCTAssertTrue(dashboardSource.contains("case .photos: l.tr(zh: \"照片\""))
        XCTAssertTrue(dashboardSource.contains("PlantDashboardCareLogDraft"))
        XCTAssertTrue(dashboardSource.contains("careLogDraft: PlantDashboardCareLogDraft?"))
        XCTAssertTrue(dashboardSource.contains("selectedSiteSummary: PlantDashboardRoomSummary?"))
        XCTAssertTrue(dashboardSource.contains(".sheet(item: $selectedSiteSummary)"))
        XCTAssertTrue(dashboardSource.contains("PlantSiteDetailSheet("))
        XCTAssertTrue(dashboardSource.contains("careTasks(for: summary)"))
        XCTAssertTrue(dashboardSource.contains("onShowPlants: { showPlants(for: summary) }"))
        XCTAssertTrue(dashboardSource.contains("onOpenPlant: openPlantFromSite"))
        XCTAssertTrue(dashboardSource.contains("onOpenCareLog: openCareLogFromSite"))
        XCTAssertTrue(dashboardSource.contains("selectedDashboardPhoto: PlantDashboardPhotoItem?"))
        XCTAssertTrue(dashboardSource.contains(".sheet(item: $selectedDashboardPhoto)"))
        XCTAssertTrue(dashboardSource.contains("PlantDashboardPhotoDetailSheet("))
        XCTAssertTrue(dashboardSource.contains("onOpenPlant: openPlantFromPhoto"))
        XCTAssertTrue(dashboardSource.contains("showingCarePlanSheet = false"))
        XCTAssertTrue(dashboardSource.contains(".sheet(isPresented: $showingCarePlanSheet)"))
        XCTAssertTrue(dashboardSource.contains("PlantDashboardCarePlanSheet("))
        XCTAssertTrue(dashboardSource.contains("onOpenPlant: openPlantFromCarePlan"))
        XCTAssertTrue(dashboardSource.contains("onOpenCareLog: openCareLogFromCarePlan"))
        XCTAssertTrue(dashboardSource.contains("onCompleteDueTasks: completeDueTasks"))
        XCTAssertTrue(dashboardSource.contains("onDeferDueTasks: deferDueTasksOneDay"))
        XCTAssertTrue(dashboardSource.contains("onDeferTask: deferTaskOneDay"))
        XCTAssertTrue(dashboardSource.contains("onSkipTask: skipTask"))
        XCTAssertTrue(dashboardSource.contains("func deferTaskOneDay(_ task: PlantCareTaskSnapshot)"))
        XCTAssertTrue(dashboardSource.contains("func skipTask(_ task: PlantCareTaskSnapshot)"))
        XCTAssertTrue(dashboardSource.contains("\"defer:\\(task.careType.rawValue):"))
        XCTAssertTrue(dashboardSource.contains("\"skip:\\(task.careType.rawValue):"))
        XCTAssertTrue(dashboardSource.contains(".sheet(item: $careLogDraft)"))
        XCTAssertTrue(dashboardSource.contains("PlantCareLogSheet("))
        XCTAssertTrue(dashboardSource.contains("openCareLogSheet(for: plant, type: .watering)"))
        XCTAssertTrue(dashboardSource.contains("openCareLogSheet(for: plant, type: task.careType)"))
        XCTAssertTrue(dashboardSource.contains("savePlantCareLog(for: draft.plant"))
        XCTAssertTrue(dashboardSource.contains("photoData: photoData"))
        XCTAssertTrue(dashboardSource.contains("healthStatus: healthStatus"))
        XCTAssertTrue(dashboardSource.contains("sitesDashboardSection"))
        XCTAssertTrue(dashboardSource.contains("plantsDashboardSection"))
        XCTAssertTrue(dashboardSource.contains("photosDashboardSection"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-sites-view"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-plants-view"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-photos-view"))
        XCTAssertTrue(dashboardSource.contains("sitesModeHeader"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-sites-header"))
        XCTAssertTrue(dashboardSource.contains("plantsModeBanner"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-plants-banner"))
        XCTAssertTrue(dashboardSource.contains("plantsModeBannerTitle"))
        XCTAssertTrue(dashboardSource.contains("plantsModeBannerSubtitle"))
        XCTAssertTrue(dashboardSource.contains("siteCard("))
        XCTAssertTrue(dashboardSource.contains("siteImageMosaic"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-site-card"))
        XCTAssertTrue(dashboardSource.contains("selectedSiteSummary = summary"))
        XCTAssertTrue(dashboardSource.contains("showPlants(for summary: PlantDashboardRoomSummary)"))
        XCTAssertTrue(dashboardSource.contains("openCareLogFromSite(plant: Plant, type: PlantCareType)"))
        XCTAssertTrue(dashboardSource.contains("Open site detail"))
        XCTAssertTrue(dashboardSource.contains("selectedDashboardMode = .plants"))
        XCTAssertTrue(dashboardSource.contains("PlantDashboardPhotoTile"))
        XCTAssertTrue(dashboardSource.contains("PlantDashboardPhotoItem"))
        XCTAssertTrue(dashboardSource.contains("let photoDate: Date?"))
        XCTAssertTrue(dashboardSource.contains("photoDashboardItems"))
        XCTAssertTrue(dashboardSource.contains("PlantDashboardPhotoPolicy.maxLogsToInspectPerPlant"))
        XCTAssertTrue(dashboardSource.contains("PlantDashboardPhotoPolicy.maxDashboardItems"))
        XCTAssertTrue(dashboardSource.contains("photoDate: log.date"))
        XCTAssertTrue(dashboardSource.contains("if (lhs.imageData != nil) != (rhs.imageData != nil)"))
        XCTAssertTrue(dashboardSource.contains("photoDashboardCard"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-photo-card"))
        XCTAssertTrue(dashboardSource.contains("photoJournalSummaryCard(items)"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-photo-journal-summary"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-photo-log-missing"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-photo-open-latest"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-photo-metric-\\(id)"))
        XCTAssertTrue(dashboardSource.contains("zh: \"有照片后，位置和照片视图会更像真实植物档案。\""))
        XCTAssertTrue(dashboardSource.contains("openCareLogSheet(for: firstMissing, type: .photo)"))
        XCTAssertTrue(dashboardSource.contains("photoDashboardAccessibilityLabel"))
        XCTAssertTrue(dashboardSource.contains("shortDate"))
        XCTAssertTrue(dashboardSource.contains("AttachmentImageDecoder.decode"))
        XCTAssertTrue(dashboardSource.contains("selectedDashboardPhoto = item"))
        XCTAssertTrue(dashboardSource.contains("openPlantFromPhoto(_ plantID: UUID)"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-care-plan-open"))
        XCTAssertTrue(dashboardSource.contains("openPlantFromCarePlan(_ plantID: UUID)"))
        XCTAssertTrue(dashboardSource.contains("openCareLogFromCarePlan(plant: Plant, type: PlantCareType)"))
        XCTAssertTrue(dashboardSource.contains("OhanaFrameScheduler.waitAfterNextFrame()"))
        XCTAssertTrue(dashboardSource.contains("PlantDashboardReadinessItem"))
        XCTAssertTrue(dashboardSource.contains("profileReadinessItems"))
        XCTAssertTrue(dashboardSource.contains("profileReadinessSection"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-profile-readiness"))
        XCTAssertTrue(dashboardSource.contains("profileReadinessRow"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-profile-readiness-row-\\(item.id)"))
        XCTAssertTrue(dashboardSource.contains("profileReadinessItem(for:)"))
        XCTAssertTrue(dashboardSource.contains("needsSafetyReview"))
        XCTAssertTrue(dashboardSource.contains("profileReadinessAccessibilityLabel"))
        XCTAssertTrue(dashboardSource.contains("onboardingHasPets"))
        XCTAssertTrue(dashboardSource.contains("onboardingHasChildren"))
        XCTAssertTrue(dashboardSource.contains("previewImageData(for: plant) == nil"))
        XCTAssertTrue(dashboardSource.contains("plantListSection"))
        XCTAssertTrue(dashboardSource.contains("plantListRow"))
        XCTAssertTrue(dashboardSource.contains("expandedPlantCardID"))
        XCTAssertTrue(dashboardSource.contains("FocusCard.fromPlant("))
        XCTAssertTrue(dashboardSource.contains("FocusHomeWalletCardContent("))
        XCTAssertTrue(dashboardSource.contains("presentation: .plant"))
        XCTAssertTrue(dashboardSource.contains("plantWalletQuickActions"))
        XCTAssertTrue(dashboardSource.contains("plantWalletQuickActionButton"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-plant-row"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-plant-open-\\(plant.id.uuidString)"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-plant-quick-care-\\(plant.id.uuidString)"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-plant-quick-fertilize-\\(plant.id.uuidString)"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-plant-growth-\\(plant.id.uuidString)"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-plant-detail-\\(plant.id.uuidString)"))
        XCTAssertTrue(dashboardSource.contains("plantListMetricPill"))
        XCTAssertTrue(dashboardSource.contains("plantCardAccessibilityLabel(for: plant, nextTask: nextTask)"))
        XCTAssertTrue(dashboardSource.contains("plantProfileCompletionPercent(for: plant)"))
        XCTAssertTrue(dashboardSource.contains("openCareLogSheet(for: plant, type: .watering)"))
        XCTAssertTrue(dashboardSource.contains("openCareLogSheet(for: plant, type: .fertilizing)"))
        XCTAssertTrue(dashboardSource.contains("plantsNeedingCareCount"))
        XCTAssertTrue(dashboardSource.contains("watchedPlantsCount"))
        XCTAssertTrue(dashboardSource.contains("nextCareStrip"))
        XCTAssertTrue(dashboardSource.contains("careWindowTasks"))
        XCTAssertTrue(dashboardSource.contains("ForEach(careWindowTasks.prefix(4))"))
        XCTAssertTrue(dashboardSource.contains("roomCareMapSection"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-room-map"))
        XCTAssertFalse(dashboardSectionsSource.contains("All locations"))
        XCTAssertFalse(dashboardSectionsSource.contains("selectedLocation ?? l.tr(zh: \"位置\""))
        XCTAssertTrue(dashboardSource.contains("roomCareSummaries"))
        XCTAssertTrue(dashboardSource.contains("PlantDashboardRoomSummary"))
        XCTAssertTrue(dashboardSource.contains("roomZoneAccessibilityLabel"))
        XCTAssertTrue(dashboardSource.contains("selectedLocation = isSelected ? nil : summary.id"))
        XCTAssertTrue(dashboardSource.contains("showsRoomEdgeRail"))
        XCTAssertTrue(dashboardSource.contains("expandedPlantCardID == nil"))
        XCTAssertTrue(dashboardSource.contains("plantHeroDirection == 0"))
        XCTAssertTrue(dashboardSource.contains("roomEdgeRail"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-room-edge-rail"))
        XCTAssertTrue(dashboardSource.contains("roomEdgeRailButton"))
        XCTAssertTrue(dashboardSource.contains("roomEdgeRailAccessibilityLabel"))
        XCTAssertTrue(dashboardSource.contains("selectRoomFromEdgeRail"))
        XCTAssertTrue(dashboardSource.contains("collapseExpandedPlantIfNeeded()"))
        XCTAssertTrue(settingsDebugSource.contains("return min(max(count, 1), 12)"))
        XCTAssertTrue(plantUITestSource.contains("testPlantWalletLongListScrollsPastSixCardsWithoutCrowdingTopViewport"))
        XCTAssertTrue(plantUITestSource.contains("plantBaselineSeedCount: 8"))
        XCTAssertTrue(plantUITestSource.contains("exactly six tappable cards in the first top viewport"))
        XCTAssertTrue(plantUITestSource.contains("At least one seeded plant card should require vertical scrolling after the first six."))
        XCTAssertTrue(plantUITestSource.contains("openFunctionMenuPlantsGroupFromPlantsTab"))
        XCTAssertTrue(plantUITestSource.contains("home-fab-shortcut-feature-group-plants"))
        XCTAssertTrue(dashboardSource.contains("searchAndFilterSection"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-search-field"))
        XCTAssertTrue(dashboardSource.contains("searchFocused: Bool"))
        XCTAssertTrue(dashboardSource.contains("plantMatchesSearch"))
        XCTAssertTrue(dashboardSource.contains("PlantCatalog.entry(id: plant.catalogSpeciesId)"))
        XCTAssertTrue(dashboardSource.contains("normalizedForPlantSearch"))
        XCTAssertTrue(dashboardSource.contains("plantSearchEmptyState"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-search-reset"))
        XCTAssertTrue(dashboardSource.contains("isNarrowingPlants"))
        XCTAssertTrue(dashboardSource.contains("transaction.animation = nil"))
        XCTAssertTrue(dashboardSource.contains("locationSummary(for: plant)"))
        XCTAssertTrue(dashboardSource.contains("plantCardAccessibilityLabel"))
        XCTAssertTrue(dashboardSource.contains("careSymbol(for: task.careType)"))
        XCTAssertFalse(dashboardSource.contains("legacyPlantListCardPreview"))
        XCTAssertFalse(dashboardSource.contains("careType.emoji"))
        XCTAssertFalse(dashboardSource.contains(".cyan"))
        XCTAssertFalse(dashboardSource.contains(".orange"))
        XCTAssertFalse(dashboardSource.contains("Text(\"🌱\")"))
        XCTAssertFalse(dashboardSource.contains("Text(\" \")"))
    }

    func testPlantSiteDetailSheetMakesSitesOperational() throws {
        let rootURL = repositoryRootURL()
        let siteSheetSource = try source("Ohana/Features/Plants/Views/PlantSiteDetailSheet.swift", rootURL: rootURL)

        XCTAssertTrue(siteSheetSource.contains("struct PlantSiteDetailSheet"))
        XCTAssertTrue(siteSheetSource.contains("let siteName: String"))
        XCTAssertTrue(siteSheetSource.contains("let plants: [Plant]"))
        XCTAssertTrue(siteSheetSource.contains("let careTasks: [PlantCareTaskSnapshot]"))
        XCTAssertTrue(siteSheetSource.contains("let onShowPlants: () -> Void"))
        XCTAssertTrue(siteSheetSource.contains("let onOpenPlant: (UUID) -> Void"))
        XCTAssertTrue(siteSheetSource.contains("let onOpenCareLog: (Plant, PlantCareType) -> Void"))
        XCTAssertTrue(siteSheetSource.contains("plant-site-detail-sheet"))
        XCTAssertTrue(siteSheetSource.contains("headerCard"))
        XCTAssertTrue(siteSheetSource.contains("dueCareSection"))
        XCTAssertTrue(siteSheetSource.contains("plant-site-detail-due-care"))
        XCTAssertTrue(siteSheetSource.contains("plantListSection"))
        XCTAssertTrue(siteSheetSource.contains("plant-site-detail-plants"))
        XCTAssertTrue(siteSheetSource.contains("plant-site-detail-view-plants"))
        XCTAssertTrue(siteSheetSource.contains("plant-site-detail-care-task-\\(task.id)"))
        XCTAssertTrue(siteSheetSource.contains("plant-site-detail-plant-row-\\(plant.id.uuidString)"))
        XCTAssertTrue(siteSheetSource.contains("onOpenCareLog(plant, task.careType)"))
        XCTAssertTrue(siteSheetSource.contains("onOpenPlant(plant.id)"))
        XCTAssertTrue(siteSheetSource.contains("AttachmentImageDecoder.decode"))
        XCTAssertTrue(siteSheetSource.contains("PlantSiteImageTile"))
        XCTAssertFalse(siteSheetSource.contains("Text(\"🌱\")"))
    }

    func testPlantDashboardPhotoDetailSheetMakesPhotosInspectable() throws {
        let rootURL = repositoryRootURL()
        let photoSheetSource = try source("Ohana/Features/Plants/Views/PlantDashboardPhotoDetailSheet.swift", rootURL: rootURL)

        XCTAssertTrue(photoSheetSource.contains("struct PlantDashboardPhotoDetailSheet"))
        XCTAssertTrue(photoSheetSource.contains("let item: PlantDashboardPhotoItem"))
        XCTAssertTrue(photoSheetSource.contains("let onOpenPlant: (UUID) -> Void"))
        XCTAssertTrue(photoSheetSource.contains("plant-dashboard-photo-detail-sheet"))
        XCTAssertTrue(photoSheetSource.contains("photoPreview"))
        XCTAssertTrue(photoSheetSource.contains("contextCard"))
        XCTAssertTrue(photoSheetSource.contains("plant-dashboard-photo-detail-context"))
        XCTAssertTrue(photoSheetSource.contains("plant-dashboard-photo-detail-open-plant"))
        XCTAssertTrue(photoSheetSource.contains("onOpenPlant(item.plant.id)"))
        XCTAssertTrue(photoSheetSource.contains("item.imageData == nil"))
        XCTAssertTrue(photoSheetSource.contains("PlantDashboardPhotoPreviewTile"))
        XCTAssertTrue(photoSheetSource.contains("AttachmentImageDecoder.decode"))
        XCTAssertTrue(photoSheetSource.contains("photoAccessibilityLabel"))
        XCTAssertFalse(photoSheetSource.contains("Text(\"🌱\")"))
    }

    func testPlantDashboardCarePlanSheetMakesTaskWindowActionable() throws {
        let rootURL = repositoryRootURL()
        let carePlanSheetSource = try source("Ohana/Features/Plants/Views/PlantDashboardCarePlanSheet.swift", rootURL: rootURL)

        XCTAssertTrue(carePlanSheetSource.contains("struct PlantDashboardCarePlanSheet"))
        XCTAssertTrue(carePlanSheetSource.contains("let plants: [Plant]"))
        XCTAssertTrue(carePlanSheetSource.contains("let careTasks: [PlantCareTaskSnapshot]"))
        XCTAssertTrue(carePlanSheetSource.contains("let onOpenPlant: (UUID) -> Void"))
        XCTAssertTrue(carePlanSheetSource.contains("let onOpenCareLog: (Plant, PlantCareType) -> Void"))
        XCTAssertTrue(carePlanSheetSource.contains("let onCompleteDueTasks: () -> Void"))
        XCTAssertTrue(carePlanSheetSource.contains("let onDeferDueTasks: () -> Void"))
        XCTAssertTrue(carePlanSheetSource.contains("let onDeferTask: (PlantCareTaskSnapshot) -> Void"))
        XCTAssertTrue(carePlanSheetSource.contains("let onSkipTask: (PlantCareTaskSnapshot) -> Void"))
        XCTAssertTrue(carePlanSheetSource.contains("plant-dashboard-care-plan-sheet"))
        XCTAssertTrue(carePlanSheetSource.contains("plant-dashboard-care-plan-due"))
        XCTAssertTrue(carePlanSheetSource.contains("plant-dashboard-care-plan-upcoming"))
        XCTAssertTrue(carePlanSheetSource.contains("plant-dashboard-care-plan-complete-all"))
        XCTAssertTrue(carePlanSheetSource.contains("plant-dashboard-care-plan-defer-all"))
        XCTAssertTrue(carePlanSheetSource.contains("plant-dashboard-care-plan-task-\\(task.id)"))
        XCTAssertTrue(carePlanSheetSource.contains("plant-dashboard-care-plan-task-defer-\\(task.id)"))
        XCTAssertTrue(carePlanSheetSource.contains("plant-dashboard-care-plan-task-skip-\\(task.id)"))
        XCTAssertTrue(carePlanSheetSource.contains("onDeferTask(task)"))
        XCTAssertTrue(carePlanSheetSource.contains("onSkipTask(task)"))
        XCTAssertTrue(carePlanSheetSource.contains("taskFeedbackButton("))
        XCTAssertTrue(carePlanSheetSource.contains("onOpenCareLog(plant, task.careType)"))
        XCTAssertTrue(carePlanSheetSource.contains("onOpenPlant(plant.id)"))
        XCTAssertTrue(carePlanSheetSource.contains("dueText(for: task)"))
        XCTAssertTrue(carePlanSheetSource.contains("careSymbol(for: task.careType)"))
        XCTAssertFalse(carePlanSheetSource.contains("Text(\"🌱\")"))
    }

    func testPlantFunctionMenuExposesDashboardListAndPhotoEntrypoints() throws {
        let rootURL = repositoryRootURL()
        let modelSource = try source("Ohana/Features/FunctionMenu/FunctionMenuModels.swift", rootURL: rootURL)
        let groupSource = try source("Ohana/Features/FunctionMenu/Views/FeatureGroupDashboardView.swift", rootURL: rootURL)
        let routerSource = try source("Ohana/Features/FunctionMenu/Views/FunctionMenuDestinationRouter.swift", rootURL: rootURL)
        let guardSource = try source("Ohana/App/AppFeatureRouteGuard.swift", rootURL: rootURL)
        let unlockSource = try source("Ohana/Features/GrowthUnlock/GrowthUnlockPolicy.swift", rootURL: rootURL)
        let sheetSource = try source("Ohana/Features/FunctionMenu/Views/FunctionMenuSheet.swift", rootURL: rootURL)

        XCTAssertTrue(modelSource.contains("case plantsDashboard"))
        XCTAssertTrue(modelSource.contains("case plantsList"))
        XCTAssertTrue(modelSource.contains("case plantsPhotos"))
        XCTAssertTrue(modelSource.contains("case plantsCalendar"))
        XCTAssertTrue(groupSource.contains("id: \"plants-dashboard\""))
        XCTAssertTrue(groupSource.contains("id: \"plants-list\""))
        XCTAssertTrue(groupSource.contains("id: \"plants-photos\""))
        XCTAssertTrue(groupSource.contains("id: \"plants-calendar\""))
        XCTAssertTrue(groupSource.contains("title: l.tr(zh: \"植物总览\", en: \"Plant Overview\""))
        XCTAssertTrue(groupSource.contains("title: l.tr(zh: \"植物列表\", en: \"Plant List\""))
        XCTAssertTrue(groupSource.contains("title: l.tr(zh: \"成长照片\", en: \"Growth Photos\""))
        XCTAssertTrue(groupSource.contains("title: l.tr(zh: \"植物日历\", en: \"Plant Calendar\""))
        XCTAssertTrue(groupSource.contains("accessibilityIdentifier(\"function-menu-group-segment-\\(item.id)"))
        XCTAssertTrue(groupSource.contains("accessibilityValue(effectiveSelectedItemID == item.id"))
        XCTAssertTrue(groupSource.contains("content(for: selectedItem)"))
        XCTAssertFalse(groupSource.contains("TabView(selection:"))
        XCTAssertTrue(groupSource.contains("let plants: [Plant]"))
        XCTAssertTrue(groupSource.contains("initialMode: .sites"))
        XCTAssertTrue(groupSource.contains("initialMode: .plants"))
        XCTAssertTrue(groupSource.contains("initialMode: .photos"))
        XCTAssertTrue(groupSource.contains("case .plantsCalendar:"))
        XCTAssertTrue(groupSource.contains("FunctionMenuDestinationRouter("))
        XCTAssertTrue(routerSource.contains("plants: plants"))
        XCTAssertTrue(routerSource.contains("case .plantsList"))
        XCTAssertTrue(routerSource.contains("case .plantsPhotos"))
        XCTAssertTrue(routerSource.contains("case .plantsCalendar"))
        XCTAssertTrue(guardSource.contains("case .plantsDashboard, .plantsList, .plantsPhotos, .plantsCalendar, .plantDetail"))
        XCTAssertTrue(unlockSource.contains("case .plantsDashboard, .plantsList, .plantsPhotos, .plantsCalendar, .plantDetail"))
        XCTAssertTrue(sheetSource.contains("case .plantsList"))
        XCTAssertTrue(sheetSource.contains("case .plantsPhotos"))
        XCTAssertTrue(sheetSource.contains("case .plantsCalendar"))
    }

    func testPlantReminderSettingsReadsLikeReminderHub() throws {
        let rootURL = repositoryRootURL()
        let settingsSource = try source("Ohana/Features/Settings/Views/SettingsPlantReminderDataContainer.swift", rootURL: rootURL)

        XCTAssertTrue(settingsSource.contains("reminderOverview"))
        XCTAssertTrue(settingsSource.contains("settings-plant-reminders-overview"))
        XCTAssertTrue(settingsSource.contains("settings-plant-reminders-overview-metric-\\(id)"))
        XCTAssertTrue(settingsSource.contains("settings-plant-reminders-state-badge"))
        XCTAssertTrue(settingsSource.contains("settings-plant-reminders-effect"))
        XCTAssertTrue(settingsSource.contains("reminderOverviewTitle"))
        XCTAssertTrue(settingsSource.contains("reminderOverviewSubtitle"))
        XCTAssertTrue(settingsSource.contains("reminderEffectText"))
        XCTAssertTrue(settingsSource.contains("enabledPlantReminderCount"))
        XCTAssertTrue(settingsSource.contains("mutedPlantReminderCount"))
        XCTAssertTrue(settingsSource.contains("enabledCareTypeReminderCount"))
        XCTAssertTrue(settingsSource.contains("careTypeReminderSummary(for: type)"))
        XCTAssertTrue(settingsSource.contains("settingsIcon(careSymbol(for: type), color: careTint(for: type))"))
        XCTAssertTrue(settingsSource.contains("settings-plant-reminders-care-type-\\(type.rawValue)"))
        XCTAssertTrue(settingsSource.contains("plantReminderAvatar(for: plant)"))
        XCTAssertTrue(settingsSource.contains("plantReminderRowSubtitle(for: plant)"))
        XCTAssertTrue(settingsSource.contains("settings-plant-reminders-plant-row-\\(plant.id.uuidString)"))
        XCTAssertTrue(settingsSource.contains("appServices.plantReminderControls.resyncPlans"))
        XCTAssertTrue(settingsSource.contains("appServices.plantReminderControls.setPlantRemindersEnabled"))
        XCTAssertTrue(settingsSource.contains("deferDueTasksOneDay"))
        XCTAssertFalse(settingsSource.contains("Text(type.emoji)"))
        XCTAssertFalse(settingsSource.contains("plant.avatarEmoji.isEmpty"))
    }

    func testPlantDetailKeepsCompleteProfileSections() throws {
        let rootURL = repositoryRootURL()
        let detailBaseSource = try source("Ohana/Features/Plants/Views/PlantDetailView.swift", rootURL: rootURL)
        let careSectionsSource = try source("Ohana/Features/Plants/Views/PlantDetailView+CareSections.swift", rootURL: rootURL)
        let healthGrowthSectionsSource = try source("Ohana/Features/Plants/Views/PlantDetailView+HealthGrowthSections.swift", rootURL: rootURL)
        let heroTimelineDeleteSource = try source("Ohana/Features/Plants/Views/PlantDetailView+HeroTimelineDelete.swift", rootURL: rootURL)
        let actionsSource = try source("Ohana/Features/Plants/Views/PlantDetailView+Actions.swift", rootURL: rootURL)
        let detailSource = [
            detailBaseSource,
            careSectionsSource,
            healthGrowthSectionsSource,
            heroTimelineDeleteSource,
            actionsSource
        ].joined(separator: "\n")
        let supportSource = try source("Ohana/Features/Plants/Views/PlantDetailView+Support.swift", rootURL: rootURL)
        let gallerySource = try source("Ohana/Features/Plants/Views/PlantDetailPhotoGallerySheet.swift", rootURL: rootURL)
        let featureHubSource = try source("Ohana/Features/Plants/Views/PlantAllFeaturesSheet.swift", rootURL: rootURL)
        let careLogSheetSource = try source("Ohana/Features/Plants/Views/PlantCareLogSheet.swift", rootURL: rootURL)

        XCTAssertTrue(detailSource.contains("careOverviewCard"))
        XCTAssertTrue(detailSource.contains("plant-detail-health-summary"))
        XCTAssertTrue(detailSource.contains("actionQueueCard"))
        XCTAssertTrue(detailSource.contains("plant-detail-action-queue"))
        XCTAssertTrue(detailSource.contains("actionQueueToolRail"))
        XCTAssertTrue(detailSource.contains("actionQueueToolButton"))
        XCTAssertTrue(detailSource.contains("plant-detail-action-tools"))
        XCTAssertTrue(detailSource.contains("plant-detail-action-tool-\\(id)"))
        XCTAssertTrue(detailSource.contains("action: openCareCalendar"))
        XCTAssertTrue(detailSource.contains("action: openReminderSettings"))
        XCTAssertTrue(detailSource.contains("action: openPlantPhotos"))
        XCTAssertTrue(detailSource.contains("func openCareCalendar()"))
        XCTAssertTrue(detailSource.contains("func openReminderSettings()"))
        XCTAssertTrue(detailSource.contains("func openPlantPhotos()"))
        XCTAssertTrue(detailSource.contains("PlantDetailActionItem"))
        XCTAssertTrue(detailSource.contains("careActionItems"))
        XCTAssertTrue(detailSource.contains("performActionQueueItem"))
        XCTAssertTrue(detailSource.contains("profileCompletionPercent"))
        XCTAssertTrue(detailSource.contains("careRhythmCard"))
        XCTAssertTrue(detailSource.contains("plant-detail-care-rhythm"))
        XCTAssertTrue(detailSource.contains("carePlanInsightCard"))
        XCTAssertTrue(detailSource.contains("plant-detail-care-plan-insights"))
        XCTAssertTrue(detailSource.contains("PlantCarePlanInsight"))
        XCTAssertTrue(detailSource.contains("PlantPlacementFitItem"))
        XCTAssertTrue(detailSource.contains("PlantSeasonalCareItem"))
        XCTAssertTrue(detailSource.contains("environmentPlanFactors"))
        XCTAssertTrue(detailSource.contains("healthCarePlanInsight"))
        XCTAssertTrue(detailSource.contains("placementFitItems"))
        XCTAssertTrue(detailSource.contains("placementLightFitItem"))
        XCTAssertTrue(detailSource.contains("placementSafetyFitItem"))
        XCTAssertTrue(detailSource.contains("placementEnvironmentFitItem"))
        XCTAssertTrue(detailSource.contains("seasonalCareItems"))
        XCTAssertTrue(detailSource.contains("seasonalGuidanceTitle"))
        XCTAssertTrue(detailSource.contains("seasonalGuidanceSummary"))
        XCTAssertTrue(detailSource.contains("placementFitCard"))
        XCTAssertTrue(detailSource.contains("seasonalGuidanceCard"))
        XCTAssertTrue(detailSource.contains("carePlanInsightRow"))
        XCTAssertTrue(careSectionsSource.contains("plant-detail-placement-fit"))
        XCTAssertTrue(careSectionsSource.contains("plant-detail-placement-fit-\\(item.id)"))
        XCTAssertTrue(careSectionsSource.contains("plant-detail-seasonal-guidance"))
        XCTAssertTrue(careSectionsSource.contains("plant-detail-seasonal-guidance-\\(item.id)"))
        XCTAssertTrue(detailSource.contains("plant-detail-care-plan-edit-profile"))
        XCTAssertTrue(detailSource.contains("func skipTask(_ task: PlantCareTaskSnapshot"))
        XCTAssertTrue(detailSource.contains("\"skip:\\(task.careType.rawValue):"))
        XCTAssertTrue(careSectionsSource.contains("plant-detail-action-skip-\\(item.id)"))
        XCTAssertTrue(careSectionsSource.contains("plant-detail-next-task-skip"))
        XCTAssertTrue(detailSource.contains("PlantHealthReviewSignal"))
        XCTAssertTrue(detailSource.contains("healthReviewCard"))
        XCTAssertTrue(detailSource.contains("plant-detail-health-review"))
        XCTAssertTrue(detailSource.contains("healthReviewSignals"))
        XCTAssertTrue(detailSource.contains("recentStressSignalLogs"))
        XCTAssertTrue(detailSource.contains("recentObservationLogCount"))
        XCTAssertTrue(detailSource.contains("latestHealthReviewLog"))
        XCTAssertTrue(detailSource.contains("healthReviewMetric"))
        XCTAssertTrue(detailSource.contains("healthReviewSignalRow"))
        XCTAssertTrue(detailSource.contains("plant-detail-health-review-signal-\\(signal.id)"))
        XCTAssertTrue(detailSource.contains("plant-detail-health-review-pest-check"))
        XCTAssertTrue(detailSource.contains("plant-detail-health-review-yellow-leaf"))
        XCTAssertTrue(detailSource.contains("diagnosisQuickActions"))
        XCTAssertTrue(detailSource.contains("plant-detail-diagnosis-card"))
        XCTAssertTrue(detailSource.contains("plant-detail-diagnosis-actions"))
        XCTAssertTrue(detailSource.contains("plant-detail-diagnosis-pest-check"))
        XCTAssertTrue(detailSource.contains("plant-detail-diagnosis-photo"))
        XCTAssertTrue(detailSource.contains("plant-detail-diagnosis-pest-found"))
        XCTAssertTrue(detailSource.contains("growthProfileCard"))
        XCTAssertTrue(detailSource.contains("plant-detail-growth-profile"))
        XCTAssertTrue(detailSource.contains("growthDiaryCard"))
        XCTAssertTrue(detailSource.contains("plant-detail-growth-diary"))
        XCTAssertTrue(detailSource.contains("plantGrowthDiaryExports.markdown"))
        XCTAssertTrue(detailSource.contains("plant-detail-growth-diary-export"))
        XCTAssertTrue(detailSource.contains("plant-detail-growth-diary-log-observation"))
        XCTAssertTrue(detailSource.contains("plant-detail-growth-diary-add-photo"))
        XCTAssertTrue(detailSource.contains("showingPlantDetailExtras"))
        XCTAssertTrue(detailSource.contains("advancedPlantDetailsSection"))
        XCTAssertTrue(detailSource.contains("plant-detail-advanced-section"))
        XCTAssertTrue(detailSource.contains("plant-detail-advanced-toggle"))
        XCTAssertTrue(detailSource.contains("plant-detail-advanced-content"))
        XCTAssertTrue(detailSource.contains("More plant details"))
        XCTAssertTrue(detailSource.contains("PlantDetailPhotoItem"))
        XCTAssertTrue(detailSource.contains("galleryPhotoItems"))
        XCTAssertTrue(detailSource.contains("PlantPhotoGallerySheet"))
        XCTAssertTrue(detailSource.contains("showingPhotoGallery"))
        XCTAssertTrue(detailSource.contains("photoGalleryPreviewStrip"))
        XCTAssertTrue(detailSource.contains("emptyPhotoGalleryHint"))
        XCTAssertTrue(detailSource.contains("plant-detail-photo-gallery-open"))
        XCTAssertTrue(detailSource.contains("plant-detail-photo-gallery-preview"))
        XCTAssertTrue(detailSource.contains("diaryStatPill"))
        XCTAssertTrue(detailSource.contains("catalogEntry.localizedSoil"))
        XCTAssertTrue(detailSource.contains("catalogEntry.localizedFertilizing"))
        XCTAssertTrue(detailSource.contains("catalogEntry.localizedPropagation"))
        XCTAssertTrue(detailSource.contains("catalogEntry.localizedToxicity"))
        XCTAssertTrue(detailSource.contains("plant-detail-care-timeline"))
        XCTAssertTrue(detailSource.contains("timelineSummaryStrip"))
        XCTAssertTrue(detailSource.contains("timelineLogRow"))
        XCTAssertTrue(detailSource.contains("careSymbol(for: log.careType)"))
        XCTAssertTrue(detailSource.contains("showingAllFeaturesHub"))
        XCTAssertTrue(detailSource.contains("plant-detail-all-features-action"))
        XCTAssertTrue(detailSource.contains("PlantAllFeaturesSheet"))
        XCTAssertTrue(detailSource.contains("PlantFeatureDestination"))
        XCTAssertTrue(detailSource.contains("openPlantFeatureDestination"))
        XCTAssertTrue(detailSource.contains("if galleryPhotoItems.isEmpty"))
        XCTAssertTrue(detailSource.contains("openCareLogSheet(.photo)"))
        XCTAssertTrue(detailSource.contains("case .calendar"))
        XCTAssertTrue(detailSource.contains("openCareCalendar()"))
        XCTAssertTrue(detailSource.contains("case .reminders"))
        XCTAssertTrue(detailSource.contains("openReminderSettings()"))
        XCTAssertTrue(detailSource.contains("pendingFeatureScrollTarget"))
        XCTAssertTrue(detailSource.contains("revealPlantDetailExtrasAndScroll(to:"))
        XCTAssertTrue(detailSource.contains("pendingFeatureScrollTarget = anchor"))
        XCTAssertTrue(detailSource.contains("ScrollViewReader"))
        XCTAssertTrue(detailSource.contains("PlantDetailFeatureAnchor"))
        XCTAssertTrue(detailSource.contains("case healthReview"))
        XCTAssertTrue(detailSource.contains("revealPlantDetailExtrasAndScroll(to: .healthReview)"))
        XCTAssertTrue(detailSource.contains("proxy.scrollTo"))
        XCTAssertTrue(detailSource.contains("@State var careLogDraftType"))
        XCTAssertTrue(detailSource.contains(".sheet(item: $careLogDraftType)"))
        XCTAssertTrue(detailSource.contains("PlantCareLogSheet("))
        XCTAssertTrue(detailSource.contains("openCareLogSheet(task.careType)"))
        XCTAssertTrue(detailSource.contains("openCareLogSheet(.watering)"))
        XCTAssertTrue(detailSource.contains("openCareLogSheet(.fertilizing)"))
        XCTAssertTrue(detailSource.contains("savePlantCareLog"))
        XCTAssertTrue(detailSource.contains("photoData: photoData"))
        XCTAssertTrue(detailSource.contains("healthStatus: healthStatus"))
        XCTAssertFalse(detailSource.contains("log.careType.emoji"))
        XCTAssertFalse(detailSource.contains("\"📍"))
        XCTAssertFalse(detailSource.contains(".green"))
        XCTAssertFalse(detailSource.contains(".orange"))
        XCTAssertFalse(detailSource.contains(".purple"))
        XCTAssertTrue(supportSource.contains("func plantSectionHeader"))
        XCTAssertTrue(gallerySource.contains("struct PlantPhotoGallerySheet"))
        XCTAssertTrue(gallerySource.contains("plant-detail-photo-gallery-sheet"))
        XCTAssertTrue(gallerySource.contains("plant-detail-photo-gallery-card"))
        XCTAssertTrue(gallerySource.contains("PlantPhotoDetailSheet"))
        XCTAssertTrue(gallerySource.contains("plant-detail-photo-detail-sheet"))
        XCTAssertTrue(gallerySource.contains("struct PlantDetailDecodedImageTile"))
        XCTAssertTrue(gallerySource.contains("AttachmentImageDecoder.decode"))
        XCTAssertTrue(featureHubSource.contains("enum PlantFeatureDestination"))
        XCTAssertTrue(featureHubSource.contains("struct PlantAllFeaturesSheet"))
        XCTAssertTrue(featureHubSource.contains("FeatureHubScaffold"))
        XCTAssertTrue(featureHubSource.contains("FeatureHubHeader"))
        XCTAssertTrue(featureHubSource.contains("FeatureHubMetricStrip"))
        XCTAssertTrue(featureHubSource.contains("FeatureHubSectionActionView"))
        XCTAssertTrue(featureHubSource.contains("plant-detail-all-features-sheet"))
        XCTAssertTrue(featureHubSource.contains("PlantHubFocusAction"))
        XCTAssertTrue(featureHubSource.contains("focusActionBanner"))
        XCTAssertTrue(featureHubSource.contains("focusAction"))
        XCTAssertTrue(featureHubSource.contains("nextDueTask"))
        XCTAssertTrue(featureHubSource.contains("destination(for: nextDueTask)"))
        XCTAssertTrue(featureHubSource.contains("plant-detail-feature-focus-\\(action.id)"))
        XCTAssertTrue(featureHubSource.contains("id: \"due-care\""))
        XCTAssertTrue(featureHubSource.contains("id: \"health-review\""))
        XCTAssertTrue(featureHubSource.contains("id: \"safety\""))
        XCTAssertTrue(featureHubSource.contains("id: \"profile\""))
        XCTAssertTrue(featureHubSource.contains("id: \"photos\""))
        XCTAssertTrue(featureHubSource.contains("id: \"first-log\""))
        XCTAssertTrue(featureHubSource.contains("case water"))
        XCTAssertTrue(featureHubSource.contains("case fertilize"))
        XCTAssertTrue(featureHubSource.contains("case pestCheck"))
        XCTAssertTrue(featureHubSource.contains("case leafCleaning"))
        XCTAssertTrue(featureHubSource.contains("case carePlan"))
        XCTAssertTrue(featureHubSource.contains("case calendar"))
        XCTAssertTrue(featureHubSource.contains("id: \"calendar\""))
        XCTAssertTrue(featureHubSource.contains("title: l.tr(zh: \"护理日历\""))
        XCTAssertTrue(featureHubSource.contains("计划会同步到日历和本地提醒"))
        XCTAssertTrue(featureHubSource.contains("destination: .calendar"))
        XCTAssertTrue(featureHubSource.contains("case reminders"))
        XCTAssertTrue(featureHubSource.contains("id: \"reminders\""))
        XCTAssertTrue(featureHubSource.contains("plant.remindersEnabled"))
        XCTAssertTrue(featureHubSource.contains("case healthReview"))
        XCTAssertTrue(featureHubSource.contains("id: \"healthReview\""))
        XCTAssertTrue(featureHubSource.contains("healthReviewSignalCount"))
        XCTAssertTrue(featureHubSource.contains("recentHealthReviewCount"))
        XCTAssertTrue(featureHubSource.contains("case photos"))
        XCTAssertTrue(featureHubSource.contains("case timeline"))
        XCTAssertTrue(featureHubSource.contains("case catalog"))
        XCTAssertTrue(featureHubSource.contains("case safety"))
        XCTAssertTrue(careLogSheetSource.contains("struct PlantCareLogSheet"))
        XCTAssertTrue(careLogSheetSource.contains("plant-care-log-sheet"))
        XCTAssertTrue(careLogSheetSource.contains("PlantCareLogContextItem"))
        XCTAssertTrue(careLogSheetSource.contains("PlantCareLogImpactItem"))
        XCTAssertTrue(careLogSheetSource.contains("PlantCareLogNoteSuggestion"))
        XCTAssertTrue(careLogSheetSource.contains("checkInContextCard"))
        XCTAssertTrue(careLogSheetSource.contains("plant-care-log-context"))
        XCTAssertTrue(careLogSheetSource.contains("contextMetric(_ item: PlantCareLogContextItem)"))
        XCTAssertTrue(careLogSheetSource.contains("plant-care-log-context-\\(item.id)"))
        XCTAssertTrue(careLogSheetSource.contains("saveImpactPreview"))
        XCTAssertTrue(careLogSheetSource.contains("plant-care-log-save-impact"))
        XCTAssertTrue(careLogSheetSource.contains("saveImpactItems"))
        XCTAssertTrue(careLogSheetSource.contains("saveImpactRow(_ item: PlantCareLogImpactItem)"))
        XCTAssertTrue(careLogSheetSource.contains("plant-care-log-impact-\\(item.id)"))
        XCTAssertTrue(careLogSheetSource.contains("careLogImpactDetail"))
        XCTAssertTrue(careLogSheetSource.contains("plant-care-log-type-\\(type.rawValue)"))
        XCTAssertTrue(careLogSheetSource.contains("plant-care-log-health-\\(status.rawValue)"))
        XCTAssertTrue(careLogSheetSource.contains("suggestedNotesSection"))
        XCTAssertTrue(careLogSheetSource.contains("plant-care-log-suggested-notes"))
        XCTAssertTrue(careLogSheetSource.contains("suggestedNotes"))
        XCTAssertTrue(careLogSheetSource.contains("appendSuggestedNote(_ text: String)"))
        XCTAssertTrue(careLogSheetSource.contains("plant-care-log-note-suggestion-\\(suggestion.id)"))
        XCTAssertTrue(careLogSheetSource.contains("plant-care-log-note"))
        XCTAssertTrue(careLogSheetSource.contains("plant-care-log-save"))
        XCTAssertTrue(careLogSheetSource.contains("GoDraftTextEditor"))
        XCTAssertTrue(careLogSheetSource.contains("PlantHealthStatus.allCases"))
        XCTAssertTrue(careLogSheetSource.contains("careTypeHint"))
        XCTAssertTrue(careLogSheetSource.contains("import PhotosUI"))
        XCTAssertTrue(careLogSheetSource.contains("@State private var selectedPhotoItem"))
        XCTAssertTrue(careLogSheetSource.contains("@State private var selectedPhotoData"))
        XCTAssertTrue(careLogSheetSource.contains("PhotosPicker(selection: $selectedPhotoItem, matching: .images)"))
        XCTAssertTrue(careLogSheetSource.contains("plant-care-log-photo-picker"))
        XCTAssertTrue(careLogSheetSource.contains("plant-care-log-photo-preview"))
        XCTAssertTrue(careLogSheetSource.contains("plant-care-log-photo-replace"))
        XCTAssertTrue(careLogSheetSource.contains("plant-care-log-photo-remove"))
        XCTAssertTrue(careLogSheetSource.contains("selectedCareType = .photo"))
        XCTAssertTrue(careLogSheetSource.contains("onSave(selectedCareType, trimmedNote"))
        XCTAssertTrue(careLogSheetSource.contains("selectedHealthStatus, selectedPhotoData"))
        XCTAssertFalse(careLogSheetSource.contains("Text(\"🌱\")"))
    }

    func testPlantCareCalendarOpensFilteredCalendarRoute() throws {
        let rootURL = repositoryRootURL()
        let detailBaseSource = try source("Ohana/Features/Plants/Views/PlantDetailView.swift", rootURL: rootURL)
        let detailActionsSource = try source("Ohana/Features/Plants/Views/PlantDetailView+Actions.swift", rootURL: rootURL)
        let detailSource = [detailBaseSource, detailActionsSource].joined(separator: "\n")
        let detailContainerSource = try source("Ohana/Features/Plants/PlantDetailDataContainer.swift", rootURL: rootURL)
        let plantRouteSource = try source("Ohana/Features/Plants/PlantRouteContainer.swift", rootURL: rootURL)
        let appRouteSource = try source("Ohana/App/RouteContainers/AppRouteDestinationContainers.swift", rootURL: rootURL)
        let contentSource = try source("Ohana/App/ContentView.swift", rootURL: rootURL)
        let functionMenuModelsSource = try source("Ohana/Features/FunctionMenu/FunctionMenuModels.swift", rootURL: rootURL)
        let functionMenuRouterSource = try source(
            "Ohana/Features/FunctionMenu/Views/FunctionMenuDestinationRouter.swift",
            rootURL: rootURL
        )
        let functionMenuGuardSource = try source("Ohana/App/AppFeatureRouteGuard.swift", rootURL: rootURL)
        let calendarSource = try source("Ohana/Features/Calendar/Views/CalendarView.swift", rootURL: rootURL)
        let calendarContentSource = try source(
            "Ohana/Features/Calendar/Views/CalendarView+Content.swift",
            rootURL: rootURL
        )
        let calendarSupportSource = try source(
            "Ohana/Features/Calendar/Views/CalendarViewSupport.swift",
            rootURL: rootURL
        )

        XCTAssertTrue(detailSource.contains("let onOpenCalendar: (UUID) -> Void"))
        XCTAssertTrue(detailSource.contains("case .calendar"))
        XCTAssertTrue(detailSource.contains("showingAllFeaturesHub = false"))
        XCTAssertTrue(detailSource.contains("onOpenCalendar(plant.id)"))
        XCTAssertTrue(detailContainerSource.contains("onOpenCalendar: @escaping (UUID) -> Void = { _ in }"))
        XCTAssertTrue(detailContainerSource.contains("onOpenCalendar: onOpenCalendar"))
        XCTAssertTrue(plantRouteSource.contains("let onOpenCalendar: (UUID) -> Void"))
        XCTAssertTrue(plantRouteSource.contains("PlantDetailView("))
        XCTAssertTrue(plantRouteSource.contains("onOpenCalendar: onOpenCalendar"))
        XCTAssertTrue(appRouteSource.contains("let onPresentPlantCalendar: ((String?) -> Void)?"))
        XCTAssertTrue(appRouteSource.contains("onPresentPlantCalendar?(plantId.uuidString)"))
        XCTAssertTrue(contentSource.contains("onPresentPlantCalendar: { entityID in"))
        XCTAssertTrue(contentSource.contains("appRoutes.presentCalendar(plantID: entityID)"))
        let functionMenuGroupSource = try source(
            "Ohana/Features/FunctionMenu/Views/FeatureGroupDashboardView.swift",
            rootURL: rootURL
        )
        let functionMenuSheetSource = try source(
            "Ohana/Features/FunctionMenu/Views/FunctionMenuSheet.swift",
            rootURL: rootURL
        )
        XCTAssertTrue(functionMenuModelsSource.contains("case plantsCalendar"))
        XCTAssertTrue(functionMenuGroupSource.contains("id: \"plants-calendar\""))
        XCTAssertTrue(functionMenuGroupSource.contains("title: l.tr(zh: \"植物日历\""))
        XCTAssertTrue(functionMenuGroupSource.contains(".plantsCalendar"))
        XCTAssertTrue(functionMenuRouterSource.contains("case .plantsCalendar:"))
        XCTAssertTrue(functionMenuRouterSource.contains("preselectedPlantId: CalendarFilterSelection.allPlants.plantId"))
        XCTAssertTrue(functionMenuSheetSource.contains("case .plantsCalendar:"))
        XCTAssertTrue(functionMenuModelsSource.contains("case plantCalendar(UUID)"))
        XCTAssertTrue(functionMenuRouterSource.contains("onOpenCalendar: { plantID in"))
        XCTAssertTrue(functionMenuRouterSource.contains("parentPath.append(FMDest.plantCalendar(plantID))"))
        XCTAssertTrue(functionMenuRouterSource.contains("case let .plantCalendar(id):"))
        XCTAssertTrue(functionMenuRouterSource.contains("preselectedPlantId: id.uuidString"))
        XCTAssertTrue(functionMenuGuardSource.contains(".plantsPhotos, .plantsCalendar, .plantDetail, .plantCalendar"))
        XCTAssertTrue(calendarSupportSource.contains("var plantId: String"))
        XCTAssertTrue(calendarSupportSource.contains("var selectedPlantId: String?"))
        XCTAssertTrue(calendarSupportSource.contains("static func plant(_ id: String)"))
        XCTAssertTrue(calendarSupportSource.contains("let plants: [Plant]"))
        XCTAssertTrue(calendarSupportSource.contains("static let allPlants"))
        XCTAssertTrue(calendarSupportSource.contains("var isAllPlantsSelected: Bool"))
        XCTAssertTrue(calendarSupportSource.contains("var isPlantScopeSelected: Bool"))
        XCTAssertTrue(calendarSupportSource.contains("var normalizedForUserFilterControls: CalendarFilterSelection"))
        XCTAssertTrue(calendarSupportSource.contains("calendar-filter-plants"))
        XCTAssertTrue(calendarSupportSource.contains("onSelect(.allPlants)"))
        XCTAssertFalse(calendarSupportSource.contains("calendar-filter-plant-\\(plant.name)"))
        XCTAssertFalse(calendarSupportSource.contains("onSelect(.plant(plant.id.uuidString))"))
        XCTAssertTrue(calendarSource.contains("@AppStorage(\"calendar_filterPlantId\")"))
        XCTAssertTrue(calendarSource.contains("var preselectedPlantId: String?"))
        XCTAssertTrue(calendarSource.contains("if let preselectedPlantId"))
        XCTAssertTrue(calendarSource.contains("return .plant(preselectedPlantId)"))
        XCTAssertTrue(calendarSource.contains("preselectedEntityIsPlant(preselectedPetId) ? .plant(preselectedPetId)"))
        XCTAssertTrue(calendarSource.contains("@State var hasUserOverriddenRouteFilter = false"))
        XCTAssertTrue(calendarSource.contains("var routeFilterSelection: CalendarFilterSelection?"))
        XCTAssertTrue(calendarSource.contains("var chipFilterSelection: CalendarFilterSelection"))
        XCTAssertTrue(calendarSource.contains("var chipFilterSelection: CalendarFilterSelection {\n        displayedFilterSelection"))
        XCTAssertTrue(calendarSource.contains("var effectiveFilterSelection: CalendarFilterSelection {\n        activeFilterSelection"))
        XCTAssertTrue(calendarSource.contains("var shouldShowInlinePetChips: Bool"))
        XCTAssertTrue(calendarSource.contains("return !hideToolbar || isMaterial"))
        XCTAssertTrue(calendarSource.contains("var effectivePlantFilterId: String?"))
        XCTAssertTrue(calendarSource.contains("var effectivePlantFilterIncludesAll: Bool"))
        XCTAssertTrue(calendarSource.contains("result.filter { eventIsRelatedToAnyPlant($0) }"))
        XCTAssertTrue(calendarSource.contains("eventIsRelatedToPlant($0, plantId: plantId)"))
        XCTAssertTrue(calendarSource.contains("func preselectedEntityIsPlant(_ entityId: String) -> Bool"))
        XCTAssertTrue(calendarSource.contains("func eventIsRelatedToPlant(_ event: Event, plantId: String) -> Bool"))
        XCTAssertTrue(calendarSource.contains("func eventIsRelatedToAnyPlant(_ event: Event) -> Bool"))
        XCTAssertTrue(calendarContentSource.contains("plants: plants"))
        XCTAssertTrue(calendarContentSource.contains("selection: chipFilterSelection"))
        XCTAssertFalse(calendarContentSource.contains("selection: displayedFilterSelection"))
        XCTAssertTrue(calendarContentSource.contains("hasUserOverriddenRouteFilter = true"))
        XCTAssertTrue(calendarContentSource.contains("func resetRouteFilterOverride()"))
        XCTAssertTrue(calendarContentSource.contains(".onChange(of: calendarFilterPlantId)"))
        XCTAssertTrue(calendarContentSource.contains(".onChange(of: preselectedPlantId)"))
        XCTAssertTrue(calendarContentSource.contains("calendarFilterPlantId = selection.plantId"))
    }

    func testPlantCareLogHealthStatusFlowsThroughCommandExecutors() throws {
        let rootURL = repositoryRootURL()
        let homeCommandSource = try source("Ohana/Features/Home/HomeCommandExecutor.swift", rootURL: rootURL)
        let memberCommandSource = try source("Ohana/Features/Members/MemberInteractionCommands.swift", rootURL: rootURL)

        XCTAssertTrue(homeCommandSource.contains("healthStatus: PlantHealthStatus? = nil"))
        XCTAssertTrue(homeCommandSource.contains("photoData: Data? = nil"))
        XCTAssertTrue(homeCommandSource.contains("photoData: photoData"))
        XCTAssertTrue(homeCommandSource.contains("healthStatus: healthStatus"))
        XCTAssertTrue(memberCommandSource.contains("healthStatus: PlantHealthStatus? = nil"))
        XCTAssertTrue(memberCommandSource.contains("photoData: photoData"))
        XCTAssertTrue(memberCommandSource.contains("healthStatus: healthStatus"))
    }

    func testPlantEditSheetShowsProfileOverviewBeforeLongForm() throws {
        let rootURL = repositoryRootURL()
        let editSource = try source("Ohana/Features/Plants/Views/PlantDetailEditSheet.swift", rootURL: rootURL)

        XCTAssertTrue(editSource.contains("editProfileOverview"))
        XCTAssertTrue(editSource.contains("plant-edit-profile-overview"))
        XCTAssertTrue(editSource.contains("profileReadinessItems"))
        XCTAssertTrue(editSource.contains("profileCompletionPercent"))
        XCTAssertTrue(editSource.contains("draftCareSummary"))
        XCTAssertTrue(editSource.contains("draftEnvironmentSummary"))
        XCTAssertTrue(editSource.contains("draftSafetySummary"))
        XCTAssertTrue(editSource.contains("editOverviewFact"))
        XCTAssertTrue(editSource.contains("PlantEditFocusSection"))
        XCTAssertTrue(editSource.contains("@State private var selectedEditFocus: PlantEditFocusSection = .all"))
        XCTAssertTrue(editSource.contains("editFocusSummary"))
        XCTAssertTrue(editSource.contains("editFocusSwitcher"))
        XCTAssertTrue(editSource.contains("plant-edit-focus-switcher"))
        XCTAssertTrue(editSource.contains("editFocusButton(_ section: PlantEditFocusSection)"))
        XCTAssertTrue(editSource.contains("plant-edit-focus-\\(section.rawValue)"))
        XCTAssertTrue(editSource.contains("editFocusTint(for section: PlantEditFocusSection)"))
        XCTAssertTrue(editSource.contains("editFocusStatus(for section: PlantEditFocusSection)"))
        XCTAssertTrue(editSource.contains("focusedEditSections"))
        XCTAssertTrue(editSource.contains("commonCatalogChoiceSection"))
        XCTAssertTrue(editSource.contains("plant-edit-common-catalog"))
        XCTAssertTrue(editSource.contains("plant-edit-common-catalog-\\(entry.id)"))
        XCTAssertTrue(editSource.contains("OhanaChoiceChipRow("))
        XCTAssertTrue(editSource.contains("plant-edit-room-choice"))
        XCTAssertTrue(editSource.contains("plant-edit-location-choice"))
        XCTAssertTrue(editSource.contains("plant-edit-pot-material-choice"))
        XCTAssertTrue(editSource.contains("plant-edit-soil-choice"))
        XCTAssertTrue(editSource.contains("plant-edit-source-choice"))
        XCTAssertTrue(editSource.contains("case .all:"))
        XCTAssertTrue(editSource.contains("case .identity:"))
        XCTAssertTrue(editSource.contains("case .care:"))
        XCTAssertTrue(editSource.contains("case .environment:"))
        XCTAssertTrue(editSource.contains("case .potting:"))
        XCTAssertTrue(editSource.contains("case .growth:"))
        XCTAssertTrue(editSource.contains("case .safety:"))
        XCTAssertTrue(editSource.contains("case .notes:"))
        XCTAssertTrue(editSource.contains("withAnimation(GoMotion.selection)"))
        XCTAssertFalse(editSource.contains(".textFieldStyle(.roundedBorder)"))
    }

    private func repositoryRootURL() -> URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
    }

    private func source(_ path: String, rootURL: URL) throws -> String {
        try String(contentsOf: rootURL.appendingPathComponent(path), encoding: .utf8)
    }
}
