import Foundation
import XCTest

final class PlantDetailExperienceTests: XCTestCase {
    func testAddPlantFlowShowsProfileReadinessAndCarePreview() throws {
        let rootURL = repositoryRootURL()
        let addPlantSource = try source("Ohana/Features/Plants/Views/AddPlantView.swift", rootURL: rootURL)

        XCTAssertTrue(addPlantSource.contains("profileSetupOverview"))
        XCTAssertTrue(addPlantSource.contains("add-plant-profile-overview"))
        XCTAssertTrue(addPlantSource.contains("profileReadinessItems"))
        XCTAssertTrue(addPlantSource.contains("profileCompletionPercent"))
        XCTAssertTrue(addPlantSource.contains("carePlanPreviewSummary"))
        XCTAssertTrue(addPlantSource.contains("Care plan preview"))
        XCTAssertTrue(addPlantSource.contains("PlantCreationOutcomeItem"))
        XCTAssertTrue(addPlantSource.contains("creationOutcomeItems"))
        XCTAssertTrue(addPlantSource.contains("creationOutcomePreview"))
        XCTAssertTrue(addPlantSource.contains("creationOutcomeRow"))
        XCTAssertTrue(addPlantSource.contains("creationSafetyAndGrowthDetail"))
        XCTAssertTrue(addPlantSource.contains("safetyOutcomeTint"))
        XCTAssertTrue(addPlantSource.contains("add-plant-creation-outcome-preview"))
        XCTAssertTrue(addPlantSource.contains("add-plant-creation-outcome-\\(item.id)"))
        XCTAssertTrue(addPlantSource.contains("id: \"home\""))
        XCTAssertTrue(addPlantSource.contains("id: \"care\""))
        XCTAssertTrue(addPlantSource.contains("id: \"safety\""))
        XCTAssertTrue(addPlantSource.contains("@FocusState private var focusedField: AddPlantFocusField?"))
        XCTAssertTrue(addPlantSource.contains("private enum AddPlantFocusField"))
        XCTAssertTrue(addPlantSource.contains(".scrollDismissesKeyboard(.interactively)"))
        XCTAssertTrue(addPlantSource.contains("keyboardFocusSpacer"))
        XCTAssertTrue(addPlantSource.contains("add-plant-keyboard-done"))
        XCTAssertTrue(addPlantSource.contains(".focused($focusedField, equals: focusField)"))
        XCTAssertTrue(addPlantSource.contains(".onSubmit { focusAfterSubmit(focusField) }"))
        XCTAssertTrue(addPlantSource.contains("focusAfterSubmit(_ field: AddPlantFocusField)"))
        XCTAssertTrue(addPlantSource.contains("focusedField = .location"))
        XCTAssertTrue(addPlantSource.contains("add-plant-pot-material-input"))
        XCTAssertTrue(addPlantSource.contains("add-plant-soil-input"))
        XCTAssertTrue(addPlantSource.contains("add-plant-source-input"))
        XCTAssertFalse(addPlantSource.contains("添加植物 🌿"))
        XCTAssertFalse(addPlantSource.contains("Add plant 🌿"))
        XCTAssertFalse(addPlantSource.contains("Pflanze hinzufügen 🌿"))
    }

    func testPlantDashboardReadsLikeCareHubInsteadOfIconGrid() throws {
        let rootURL = repositoryRootURL()
        let dashboardSource = try source("Ohana/Features/Plants/Views/PlantDashboardView.swift", rootURL: rootURL)

        XCTAssertTrue(dashboardSource.contains("enum PlantDashboardEntryMode"))
        XCTAssertTrue(dashboardSource.contains("initialMode: PlantDashboardEntryMode = .sites"))
        XCTAssertTrue(dashboardSource.contains("PlantDashboardMode(entryMode: initialMode)"))
        XCTAssertTrue(dashboardSource.contains("dashboardOverviewCard"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-overview"))
        XCTAssertTrue(dashboardSource.contains("dashboardLibraryAvatar"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-library-avatar"))
        XCTAssertTrue(dashboardSource.contains("dashboardActionCapsule"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-action-capsule"))
        XCTAssertTrue(dashboardSource.contains("dashboardStatusRibbon"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-status-ribbon"))
        XCTAssertTrue(dashboardSource.contains("dashboardStatusChip"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-status-chip-\\(id)"))
        XCTAssertTrue(dashboardSource.contains("dashboardQuickActionRail"))
        XCTAssertTrue(dashboardSource.contains("dashboardQuickActionButton"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-quick-actions"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-quick-action-\\(id)"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-open-filters"))
        XCTAssertTrue(dashboardSource.contains("openDashboardFilters()"))
        XCTAssertTrue(dashboardSource.contains("openDashboardCarePlan()"))
        XCTAssertTrue(dashboardSource.contains("openDashboardProfileQueue()"))
        XCTAssertTrue(dashboardSource.contains("openDashboardPhotos()"))
        XCTAssertTrue(dashboardSource.contains("PlantDashboardMode"))
        XCTAssertTrue(dashboardSource.contains("case photos"))
        XCTAssertTrue(dashboardSource.contains("@State private var selectedDashboardMode"))
        XCTAssertTrue(dashboardSource.contains("dashboardModePicker"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-mode-picker"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-mode-\\(mode.rawValue)"))
        XCTAssertTrue(dashboardSource.contains("case .sites: l.tr(zh: \"位置\""))
        XCTAssertTrue(dashboardSource.contains("case .plants: l.tr(zh: \"植物\""))
        XCTAssertTrue(dashboardSource.contains("case .photos: l.tr(zh: \"照片\""))
        XCTAssertTrue(dashboardSource.contains("PlantDashboardCareLogDraft"))
        XCTAssertTrue(dashboardSource.contains("@State private var careLogDraft"))
        XCTAssertTrue(dashboardSource.contains("@State private var selectedSiteSummary"))
        XCTAssertTrue(dashboardSource.contains(".sheet(item: $selectedSiteSummary)"))
        XCTAssertTrue(dashboardSource.contains("PlantSiteDetailSheet("))
        XCTAssertTrue(dashboardSource.contains("careTasks(for: summary)"))
        XCTAssertTrue(dashboardSource.contains("onShowPlants: { showPlants(for: summary) }"))
        XCTAssertTrue(dashboardSource.contains("onOpenPlant: openPlantFromSite"))
        XCTAssertTrue(dashboardSource.contains("onOpenCareLog: openCareLogFromSite"))
        XCTAssertTrue(dashboardSource.contains("@State private var selectedDashboardPhoto"))
        XCTAssertTrue(dashboardSource.contains(".sheet(item: $selectedDashboardPhoto)"))
        XCTAssertTrue(dashboardSource.contains("PlantDashboardPhotoDetailSheet("))
        XCTAssertTrue(dashboardSource.contains("onOpenPlant: openPlantFromPhoto"))
        XCTAssertTrue(dashboardSource.contains("@State private var showingCarePlanSheet"))
        XCTAssertTrue(dashboardSource.contains(".sheet(isPresented: $showingCarePlanSheet)"))
        XCTAssertTrue(dashboardSource.contains("PlantDashboardCarePlanSheet("))
        XCTAssertTrue(dashboardSource.contains("onOpenPlant: openPlantFromCarePlan"))
        XCTAssertTrue(dashboardSource.contains("onOpenCareLog: openCareLogFromCarePlan"))
        XCTAssertTrue(dashboardSource.contains("onCompleteDueTasks: completeDueTasks"))
        XCTAssertTrue(dashboardSource.contains("onDeferDueTasks: deferDueTasksOneDay"))
        XCTAssertTrue(dashboardSource.contains(".sheet(item: $careLogDraft)"))
        XCTAssertTrue(dashboardSource.contains("PlantCareLogSheet("))
        XCTAssertTrue(dashboardSource.contains("openCareLogSheet(for: plant, type: .watering)"))
        XCTAssertTrue(dashboardSource.contains("openCareLogSheet(for: plant, type: task.careType)"))
        XCTAssertTrue(dashboardSource.contains("savePlantCareLog(for: draft.plant"))
        XCTAssertTrue(dashboardSource.contains("photoData: photoData"))
        XCTAssertTrue(dashboardSource.contains("healthStatus: healthStatus"))
        XCTAssertTrue(dashboardSource.contains("sitesDashboardSection"))
        XCTAssertTrue(dashboardSource.contains("plantsDashboardSection"))
        XCTAssertTrue(dashboardSource.contains("photosDashboardSection"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-sites-view"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-plants-view"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-photos-view"))
        XCTAssertTrue(dashboardSource.contains("sitesModeHeader"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-sites-header"))
        XCTAssertTrue(dashboardSource.contains("plantsModeBanner"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-plants-banner"))
        XCTAssertTrue(dashboardSource.contains("plantsModeBannerTitle"))
        XCTAssertTrue(dashboardSource.contains("plantsModeBannerSubtitle"))
        XCTAssertTrue(dashboardSource.contains("siteCard("))
        XCTAssertTrue(dashboardSource.contains("siteImageMosaic"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-site-card"))
        XCTAssertTrue(dashboardSource.contains("selectedSiteSummary = summary"))
        XCTAssertTrue(dashboardSource.contains("showPlants(for summary: PlantDashboardRoomSummary)"))
        XCTAssertTrue(dashboardSource.contains("openCareLogFromSite(plant: Plant, type: PlantCareType)"))
        XCTAssertTrue(dashboardSource.contains("Open site detail"))
        XCTAssertTrue(dashboardSource.contains("selectedDashboardMode = .plants"))
        XCTAssertTrue(dashboardSource.contains("PlantDashboardPhotoTile"))
        XCTAssertTrue(dashboardSource.contains("PlantDashboardPhotoItem"))
        XCTAssertTrue(dashboardSource.contains("let photoDate: Date?"))
        XCTAssertTrue(dashboardSource.contains("photoDashboardItems"))
        XCTAssertTrue(dashboardSource.contains("photoDate: log.date"))
        XCTAssertTrue(dashboardSource.contains("if (lhs.imageData != nil) != (rhs.imageData != nil)"))
        XCTAssertTrue(dashboardSource.contains("photoDashboardCard"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-photo-card"))
        XCTAssertTrue(dashboardSource.contains("photoJournalSummaryCard(items)"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-photo-journal-summary"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-photo-log-missing"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-photo-open-latest"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-photo-metric-\\(id)"))
        XCTAssertTrue(dashboardSource.contains("zh: \"有照片后，位置和照片视图会更像真实植物档案。\""))
        XCTAssertTrue(dashboardSource.contains("openCareLogSheet(for: firstMissing, type: .photo)"))
        XCTAssertTrue(dashboardSource.contains("photoDashboardAccessibilityLabel"))
        XCTAssertTrue(dashboardSource.contains("shortDate"))
        XCTAssertTrue(dashboardSource.contains("AttachmentImageDecoder.decode"))
        XCTAssertTrue(dashboardSource.contains("selectedDashboardPhoto = item"))
        XCTAssertTrue(dashboardSource.contains("openPlantFromPhoto(_ plantID: UUID)"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-care-plan-open"))
        XCTAssertTrue(dashboardSource.contains("openPlantFromCarePlan(_ plantID: UUID)"))
        XCTAssertTrue(dashboardSource.contains("openCareLogFromCarePlan(plant: Plant, type: PlantCareType)"))
        XCTAssertTrue(dashboardSource.contains("OhanaFrameScheduler.waitAfterNextFrame()"))
        XCTAssertTrue(dashboardSource.contains("PlantDashboardReadinessItem"))
        XCTAssertTrue(dashboardSource.contains("profileReadinessItems"))
        XCTAssertTrue(dashboardSource.contains("profileReadinessSection"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-profile-readiness"))
        XCTAssertTrue(dashboardSource.contains("profileReadinessRow"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-profile-readiness-row-\\(item.id)"))
        XCTAssertTrue(dashboardSource.contains("profileReadinessItem(for:)"))
        XCTAssertTrue(dashboardSource.contains("needsSafetyReview"))
        XCTAssertTrue(dashboardSource.contains("profileReadinessAccessibilityLabel"))
        XCTAssertTrue(dashboardSource.contains("onboardingHasPets"))
        XCTAssertTrue(dashboardSource.contains("onboardingHasChildren"))
        XCTAssertTrue(dashboardSource.contains("previewImageData(for: plant) == nil"))
        XCTAssertTrue(dashboardSource.contains("plantListSection"))
        XCTAssertTrue(dashboardSource.contains("plantListRow"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-plant-row"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-plant-open-\\(plant.id.uuidString)"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-plant-quick-care-\\(plant.id.uuidString)"))
        XCTAssertTrue(dashboardSource.contains("plantListMetricPill"))
        XCTAssertTrue(dashboardSource.contains("plantListCarePlanSummary(for: plant, nextTask: nextTask)"))
        XCTAssertTrue(dashboardSource.contains("plantProfileCompletionPercent(for: plant)"))
        XCTAssertTrue(dashboardSource.contains("plantListQuickCareAccessibilityLabel(for: plant, nextTask: nextTask)"))
        XCTAssertTrue(dashboardSource.contains("openCareLogSheet(for: plant, type: nextTask?.careType ?? .watering)"))
        XCTAssertTrue(dashboardSource.contains("plantsNeedingCareCount"))
        XCTAssertTrue(dashboardSource.contains("watchedPlantsCount"))
        XCTAssertTrue(dashboardSource.contains("nextCareStrip"))
        XCTAssertTrue(dashboardSource.contains("careWindowTasks"))
        XCTAssertTrue(dashboardSource.contains("ForEach(careWindowTasks.prefix(4))"))
        XCTAssertTrue(dashboardSource.contains("roomCareMapSection"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-room-map"))
        XCTAssertTrue(dashboardSource.contains("if !locationOptions.isEmpty {"))
        XCTAssertTrue(dashboardSource.contains("roomCareSummaries"))
        XCTAssertTrue(dashboardSource.contains("PlantDashboardRoomSummary"))
        XCTAssertTrue(dashboardSource.contains("roomZoneAccessibilityLabel"))
        XCTAssertTrue(dashboardSource.contains("selectedLocation = isSelected ? nil : summary.id"))
        XCTAssertTrue(dashboardSource.contains("searchAndFilterSection"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-search-field"))
        XCTAssertTrue(dashboardSource.contains("@FocusState private var searchFocused"))
        XCTAssertTrue(dashboardSource.contains("plantMatchesSearch"))
        XCTAssertTrue(dashboardSource.contains("PlantCatalog.entry(id: plant.catalogSpeciesId)"))
        XCTAssertTrue(dashboardSource.contains("normalizedForPlantSearch"))
        XCTAssertTrue(dashboardSource.contains("plantSearchEmptyState"))
        XCTAssertTrue(dashboardSource.contains("plant-dashboard-search-reset"))
        XCTAssertTrue(dashboardSource.contains("isNarrowingPlants"))
        XCTAssertTrue(dashboardSource.contains("transaction.animation = nil"))
        XCTAssertTrue(dashboardSource.contains("locationSummary(for: plant)"))
        XCTAssertTrue(dashboardSource.contains("plantCardAccessibilityLabel"))
        XCTAssertTrue(dashboardSource.contains("careSymbol(for: task.careType)"))
        XCTAssertFalse(dashboardSource.contains("legacyPlantListCardPreview"))
        XCTAssertFalse(dashboardSource.contains("careType.emoji"))
        XCTAssertFalse(dashboardSource.contains(".cyan"))
        XCTAssertFalse(dashboardSource.contains(".orange"))
        XCTAssertFalse(dashboardSource.contains("Text(\"🌱\")"))
        XCTAssertFalse(dashboardSource.contains("Text(\" \")"))
    }

    func testPlantSiteDetailSheetMakesSitesOperational() throws {
        let rootURL = repositoryRootURL()
        let siteSheetSource = try source("Ohana/Features/Plants/Views/PlantSiteDetailSheet.swift", rootURL: rootURL)

        XCTAssertTrue(siteSheetSource.contains("struct PlantSiteDetailSheet"))
        XCTAssertTrue(siteSheetSource.contains("let siteName: String"))
        XCTAssertTrue(siteSheetSource.contains("let plants: [Plant]"))
        XCTAssertTrue(siteSheetSource.contains("let careTasks: [PlantCareTaskSnapshot]"))
        XCTAssertTrue(siteSheetSource.contains("let onShowPlants: () -> Void"))
        XCTAssertTrue(siteSheetSource.contains("let onOpenPlant: (UUID) -> Void"))
        XCTAssertTrue(siteSheetSource.contains("let onOpenCareLog: (Plant, PlantCareType) -> Void"))
        XCTAssertTrue(siteSheetSource.contains("plant-site-detail-sheet"))
        XCTAssertTrue(siteSheetSource.contains("headerCard"))
        XCTAssertTrue(siteSheetSource.contains("dueCareSection"))
        XCTAssertTrue(siteSheetSource.contains("plant-site-detail-due-care"))
        XCTAssertTrue(siteSheetSource.contains("plantListSection"))
        XCTAssertTrue(siteSheetSource.contains("plant-site-detail-plants"))
        XCTAssertTrue(siteSheetSource.contains("plant-site-detail-view-plants"))
        XCTAssertTrue(siteSheetSource.contains("plant-site-detail-care-task-\\(task.id)"))
        XCTAssertTrue(siteSheetSource.contains("plant-site-detail-plant-row-\\(plant.id.uuidString)"))
        XCTAssertTrue(siteSheetSource.contains("onOpenCareLog(plant, task.careType)"))
        XCTAssertTrue(siteSheetSource.contains("onOpenPlant(plant.id)"))
        XCTAssertTrue(siteSheetSource.contains("AttachmentImageDecoder.decode"))
        XCTAssertTrue(siteSheetSource.contains("PlantSiteImageTile"))
        XCTAssertFalse(siteSheetSource.contains("Text(\"🌱\")"))
    }

    func testPlantDashboardPhotoDetailSheetMakesPhotosInspectable() throws {
        let rootURL = repositoryRootURL()
        let photoSheetSource = try source("Ohana/Features/Plants/Views/PlantDashboardPhotoDetailSheet.swift", rootURL: rootURL)

        XCTAssertTrue(photoSheetSource.contains("struct PlantDashboardPhotoDetailSheet"))
        XCTAssertTrue(photoSheetSource.contains("let item: PlantDashboardPhotoItem"))
        XCTAssertTrue(photoSheetSource.contains("let onOpenPlant: (UUID) -> Void"))
        XCTAssertTrue(photoSheetSource.contains("plant-dashboard-photo-detail-sheet"))
        XCTAssertTrue(photoSheetSource.contains("photoPreview"))
        XCTAssertTrue(photoSheetSource.contains("contextCard"))
        XCTAssertTrue(photoSheetSource.contains("plant-dashboard-photo-detail-context"))
        XCTAssertTrue(photoSheetSource.contains("plant-dashboard-photo-detail-open-plant"))
        XCTAssertTrue(photoSheetSource.contains("onOpenPlant(item.plant.id)"))
        XCTAssertTrue(photoSheetSource.contains("item.imageData == nil"))
        XCTAssertTrue(photoSheetSource.contains("PlantDashboardPhotoPreviewTile"))
        XCTAssertTrue(photoSheetSource.contains("AttachmentImageDecoder.decode"))
        XCTAssertTrue(photoSheetSource.contains("photoAccessibilityLabel"))
        XCTAssertFalse(photoSheetSource.contains("Text(\"🌱\")"))
    }

    func testPlantDashboardCarePlanSheetMakesTaskWindowActionable() throws {
        let rootURL = repositoryRootURL()
        let carePlanSheetSource = try source("Ohana/Features/Plants/Views/PlantDashboardCarePlanSheet.swift", rootURL: rootURL)

        XCTAssertTrue(carePlanSheetSource.contains("struct PlantDashboardCarePlanSheet"))
        XCTAssertTrue(carePlanSheetSource.contains("let plants: [Plant]"))
        XCTAssertTrue(carePlanSheetSource.contains("let careTasks: [PlantCareTaskSnapshot]"))
        XCTAssertTrue(carePlanSheetSource.contains("let onOpenPlant: (UUID) -> Void"))
        XCTAssertTrue(carePlanSheetSource.contains("let onOpenCareLog: (Plant, PlantCareType) -> Void"))
        XCTAssertTrue(carePlanSheetSource.contains("let onCompleteDueTasks: () -> Void"))
        XCTAssertTrue(carePlanSheetSource.contains("let onDeferDueTasks: () -> Void"))
        XCTAssertTrue(carePlanSheetSource.contains("plant-dashboard-care-plan-sheet"))
        XCTAssertTrue(carePlanSheetSource.contains("plant-dashboard-care-plan-due"))
        XCTAssertTrue(carePlanSheetSource.contains("plant-dashboard-care-plan-upcoming"))
        XCTAssertTrue(carePlanSheetSource.contains("plant-dashboard-care-plan-complete-all"))
        XCTAssertTrue(carePlanSheetSource.contains("plant-dashboard-care-plan-defer-all"))
        XCTAssertTrue(carePlanSheetSource.contains("plant-dashboard-care-plan-task-\\(task.id)"))
        XCTAssertTrue(carePlanSheetSource.contains("onOpenCareLog(plant, task.careType)"))
        XCTAssertTrue(carePlanSheetSource.contains("onOpenPlant(plant.id)"))
        XCTAssertTrue(carePlanSheetSource.contains("dueText(for: task)"))
        XCTAssertTrue(carePlanSheetSource.contains("careSymbol(for: task.careType)"))
        XCTAssertFalse(carePlanSheetSource.contains("Text(\"🌱\")"))
    }

    func testPlantFunctionMenuExposesDashboardListAndPhotoEntrypoints() throws {
        let rootURL = repositoryRootURL()
        let modelSource = try source("Ohana/Features/FunctionMenu/FunctionMenuModels.swift", rootURL: rootURL)
        let groupSource = try source("Ohana/Features/FunctionMenu/Views/FeatureGroupDashboardView.swift", rootURL: rootURL)
        let routerSource = try source("Ohana/Features/FunctionMenu/Views/FunctionMenuDestinationRouter.swift", rootURL: rootURL)
        let guardSource = try source("Ohana/App/AppFeatureRouteGuard.swift", rootURL: rootURL)
        let unlockSource = try source("Ohana/Features/GrowthUnlock/GrowthUnlockPolicy.swift", rootURL: rootURL)
        let sheetSource = try source("Ohana/Features/FunctionMenu/Views/FunctionMenuSheet.swift", rootURL: rootURL)

        XCTAssertTrue(modelSource.contains("case plantsDashboard"))
        XCTAssertTrue(modelSource.contains("case plantsList"))
        XCTAssertTrue(modelSource.contains("case plantsPhotos"))
        XCTAssertTrue(groupSource.contains("destination(id: \"plants-dashboard\""))
        XCTAssertTrue(groupSource.contains("destination(id: \"plants-list\""))
        XCTAssertTrue(groupSource.contains("destination(id: \"plants-photos\""))
        XCTAssertTrue(groupSource.contains("title: \"植物总览\""))
        XCTAssertTrue(groupSource.contains("title: \"植物列表\""))
        XCTAssertTrue(groupSource.contains("title: \"成长照片\""))
        XCTAssertTrue(groupSource.contains("let plants: [Plant]"))
        XCTAssertTrue(groupSource.contains("initialMode: .sites"))
        XCTAssertTrue(groupSource.contains("initialMode: .plants"))
        XCTAssertTrue(groupSource.contains("initialMode: .photos"))
        XCTAssertTrue(routerSource.contains("plants: plants"))
        XCTAssertTrue(routerSource.contains("case .plantsList"))
        XCTAssertTrue(routerSource.contains("case .plantsPhotos"))
        XCTAssertTrue(guardSource.contains("case .plantsDashboard, .plantsList, .plantsPhotos, .plantDetail"))
        XCTAssertTrue(unlockSource.contains("case .plantsDashboard, .plantsList, .plantsPhotos, .plantDetail"))
        XCTAssertTrue(sheetSource.contains("case .plantsList"))
        XCTAssertTrue(sheetSource.contains("case .plantsPhotos"))
    }

    func testPlantReminderSettingsReadsLikeReminderHub() throws {
        let rootURL = repositoryRootURL()
        let settingsSource = try source("Ohana/Features/Settings/Views/SettingsPlantReminderDataContainer.swift", rootURL: rootURL)

        XCTAssertTrue(settingsSource.contains("reminderOverview"))
        XCTAssertTrue(settingsSource.contains("settings-plant-reminders-overview"))
        XCTAssertTrue(settingsSource.contains("settings-plant-reminders-overview-metric-\\(id)"))
        XCTAssertTrue(settingsSource.contains("settings-plant-reminders-state-badge"))
        XCTAssertTrue(settingsSource.contains("settings-plant-reminders-effect"))
        XCTAssertTrue(settingsSource.contains("reminderOverviewTitle"))
        XCTAssertTrue(settingsSource.contains("reminderOverviewSubtitle"))
        XCTAssertTrue(settingsSource.contains("reminderEffectText"))
        XCTAssertTrue(settingsSource.contains("enabledPlantReminderCount"))
        XCTAssertTrue(settingsSource.contains("mutedPlantReminderCount"))
        XCTAssertTrue(settingsSource.contains("enabledCareTypeReminderCount"))
        XCTAssertTrue(settingsSource.contains("careTypeReminderSummary(for: type)"))
        XCTAssertTrue(settingsSource.contains("settingsIcon(careSymbol(for: type), color: careTint(for: type))"))
        XCTAssertTrue(settingsSource.contains("settings-plant-reminders-care-type-\\(type.rawValue)"))
        XCTAssertTrue(settingsSource.contains("plantReminderAvatar(for: plant)"))
        XCTAssertTrue(settingsSource.contains("plantReminderRowSubtitle(for: plant)"))
        XCTAssertTrue(settingsSource.contains("settings-plant-reminders-plant-row-\\(plant.id.uuidString)"))
        XCTAssertTrue(settingsSource.contains("appServices.plantReminderControls.resyncPlans"))
        XCTAssertTrue(settingsSource.contains("appServices.plantReminderControls.setPlantRemindersEnabled"))
        XCTAssertTrue(settingsSource.contains("deferDueTasksOneDay"))
        XCTAssertFalse(settingsSource.contains("Text(type.emoji)"))
        XCTAssertFalse(settingsSource.contains("plant.avatarEmoji.isEmpty"))
    }

    func testPlantDetailKeepsCompleteProfileSections() throws {
        let rootURL = repositoryRootURL()
        let detailSource = try source("Ohana/Features/Plants/Views/PlantDetailView.swift", rootURL: rootURL)
        let supportSource = try source("Ohana/Features/Plants/Views/PlantDetailView+Support.swift", rootURL: rootURL)
        let gallerySource = try source("Ohana/Features/Plants/Views/PlantDetailPhotoGallerySheet.swift", rootURL: rootURL)
        let featureHubSource = try source("Ohana/Features/Plants/Views/PlantAllFeaturesSheet.swift", rootURL: rootURL)
        let careLogSheetSource = try source("Ohana/Features/Plants/Views/PlantCareLogSheet.swift", rootURL: rootURL)

        XCTAssertTrue(detailSource.contains("careOverviewCard"))
        XCTAssertTrue(detailSource.contains("plant-detail-health-summary"))
        XCTAssertTrue(detailSource.contains("actionQueueCard"))
        XCTAssertTrue(detailSource.contains("plant-detail-action-queue"))
        XCTAssertTrue(detailSource.contains("actionQueueToolRail"))
        XCTAssertTrue(detailSource.contains("actionQueueToolButton"))
        XCTAssertTrue(detailSource.contains("plant-detail-action-tools"))
        XCTAssertTrue(detailSource.contains("plant-detail-action-tool-\\(id)"))
        XCTAssertTrue(detailSource.contains("action: openCareCalendar"))
        XCTAssertTrue(detailSource.contains("action: openReminderSettings"))
        XCTAssertTrue(detailSource.contains("action: openPlantPhotos"))
        XCTAssertTrue(detailSource.contains("private func openCareCalendar()"))
        XCTAssertTrue(detailSource.contains("private func openReminderSettings()"))
        XCTAssertTrue(detailSource.contains("private func openPlantPhotos()"))
        XCTAssertTrue(detailSource.contains("PlantDetailActionItem"))
        XCTAssertTrue(detailSource.contains("careActionItems"))
        XCTAssertTrue(detailSource.contains("performActionQueueItem"))
        XCTAssertTrue(detailSource.contains("profileCompletionPercent"))
        XCTAssertTrue(detailSource.contains("careRhythmCard"))
        XCTAssertTrue(detailSource.contains("plant-detail-care-rhythm"))
        XCTAssertTrue(detailSource.contains("carePlanInsightCard"))
        XCTAssertTrue(detailSource.contains("plant-detail-care-plan-insights"))
        XCTAssertTrue(detailSource.contains("PlantCarePlanInsight"))
        XCTAssertTrue(detailSource.contains("environmentPlanFactors"))
        XCTAssertTrue(detailSource.contains("healthCarePlanInsight"))
        XCTAssertTrue(detailSource.contains("carePlanInsightRow"))
        XCTAssertTrue(detailSource.contains("plant-detail-care-plan-edit-profile"))
        XCTAssertTrue(detailSource.contains("PlantHealthReviewSignal"))
        XCTAssertTrue(detailSource.contains("healthReviewCard"))
        XCTAssertTrue(detailSource.contains("plant-detail-health-review"))
        XCTAssertTrue(detailSource.contains("healthReviewSignals"))
        XCTAssertTrue(detailSource.contains("recentStressSignalLogs"))
        XCTAssertTrue(detailSource.contains("recentObservationLogCount"))
        XCTAssertTrue(detailSource.contains("latestHealthReviewLog"))
        XCTAssertTrue(detailSource.contains("healthReviewMetric"))
        XCTAssertTrue(detailSource.contains("healthReviewSignalRow"))
        XCTAssertTrue(detailSource.contains("plant-detail-health-review-signal-\\(signal.id)"))
        XCTAssertTrue(detailSource.contains("plant-detail-health-review-pest-check"))
        XCTAssertTrue(detailSource.contains("plant-detail-health-review-yellow-leaf"))
        XCTAssertTrue(detailSource.contains("diagnosisQuickActions"))
        XCTAssertTrue(detailSource.contains("plant-detail-diagnosis-card"))
        XCTAssertTrue(detailSource.contains("plant-detail-diagnosis-actions"))
        XCTAssertTrue(detailSource.contains("plant-detail-diagnosis-pest-check"))
        XCTAssertTrue(detailSource.contains("plant-detail-diagnosis-photo"))
        XCTAssertTrue(detailSource.contains("plant-detail-diagnosis-pest-found"))
        XCTAssertTrue(detailSource.contains("growthProfileCard"))
        XCTAssertTrue(detailSource.contains("plant-detail-growth-profile"))
        XCTAssertTrue(detailSource.contains("growthDiaryCard"))
        XCTAssertTrue(detailSource.contains("plant-detail-growth-diary"))
        XCTAssertTrue(detailSource.contains("PlantGrowthDiaryExportService.markdown"))
        XCTAssertTrue(detailSource.contains("plant-detail-growth-diary-export"))
        XCTAssertTrue(detailSource.contains("plant-detail-growth-diary-log-observation"))
        XCTAssertTrue(detailSource.contains("plant-detail-growth-diary-add-photo"))
        XCTAssertTrue(detailSource.contains("PlantDetailPhotoItem"))
        XCTAssertTrue(detailSource.contains("galleryPhotoItems"))
        XCTAssertTrue(detailSource.contains("PlantPhotoGallerySheet"))
        XCTAssertTrue(detailSource.contains("showingPhotoGallery"))
        XCTAssertTrue(detailSource.contains("photoGalleryPreviewStrip"))
        XCTAssertTrue(detailSource.contains("emptyPhotoGalleryHint"))
        XCTAssertTrue(detailSource.contains("plant-detail-photo-gallery-open"))
        XCTAssertTrue(detailSource.contains("plant-detail-photo-gallery-preview"))
        XCTAssertTrue(detailSource.contains("diaryStatPill"))
        XCTAssertTrue(detailSource.contains("catalogEntry.localizedSoil"))
        XCTAssertTrue(detailSource.contains("catalogEntry.localizedFertilizing"))
        XCTAssertTrue(detailSource.contains("catalogEntry.localizedPropagation"))
        XCTAssertTrue(detailSource.contains("catalogEntry.localizedToxicity"))
        XCTAssertTrue(detailSource.contains("plant-detail-care-timeline"))
        XCTAssertTrue(detailSource.contains("timelineSummaryStrip"))
        XCTAssertTrue(detailSource.contains("timelineLogRow"))
        XCTAssertTrue(detailSource.contains("careSymbol(for: log.careType)"))
        XCTAssertTrue(detailSource.contains("showingAllFeaturesHub"))
        XCTAssertTrue(detailSource.contains("plant-detail-all-features-action"))
        XCTAssertTrue(detailSource.contains("PlantAllFeaturesSheet"))
        XCTAssertTrue(detailSource.contains("PlantFeatureDestination"))
        XCTAssertTrue(detailSource.contains("openPlantFeatureDestination"))
        XCTAssertTrue(detailSource.contains("if galleryPhotoItems.isEmpty"))
        XCTAssertTrue(detailSource.contains("openCareLogSheet(.photo)"))
        XCTAssertTrue(detailSource.contains("case .calendar"))
        XCTAssertTrue(detailSource.contains("openCareCalendar()"))
        XCTAssertTrue(detailSource.contains("case .reminders"))
        XCTAssertTrue(detailSource.contains("openReminderSettings()"))
        XCTAssertTrue(detailSource.contains("pendingFeatureScrollTarget"))
        XCTAssertTrue(detailSource.contains("ScrollViewReader"))
        XCTAssertTrue(detailSource.contains("PlantDetailFeatureAnchor"))
        XCTAssertTrue(detailSource.contains("case healthReview"))
        XCTAssertTrue(detailSource.contains("pendingFeatureScrollTarget = .healthReview"))
        XCTAssertTrue(detailSource.contains("proxy.scrollTo"))
        XCTAssertTrue(detailSource.contains("@State private var careLogDraftType"))
        XCTAssertTrue(detailSource.contains(".sheet(item: $careLogDraftType)"))
        XCTAssertTrue(detailSource.contains("PlantCareLogSheet("))
        XCTAssertTrue(detailSource.contains("openCareLogSheet(task.careType)"))
        XCTAssertTrue(detailSource.contains("openCareLogSheet(.watering)"))
        XCTAssertTrue(detailSource.contains("openCareLogSheet(.fertilizing)"))
        XCTAssertTrue(detailSource.contains("savePlantCareLog"))
        XCTAssertTrue(detailSource.contains("photoData: photoData"))
        XCTAssertTrue(detailSource.contains("healthStatus: healthStatus"))
        XCTAssertFalse(detailSource.contains("log.careType.emoji"))
        XCTAssertFalse(detailSource.contains("\"📍"))
        XCTAssertFalse(detailSource.contains(".green"))
        XCTAssertFalse(detailSource.contains(".orange"))
        XCTAssertFalse(detailSource.contains(".purple"))
        XCTAssertTrue(supportSource.contains("func plantSectionHeader"))
        XCTAssertTrue(gallerySource.contains("struct PlantPhotoGallerySheet"))
        XCTAssertTrue(gallerySource.contains("plant-detail-photo-gallery-sheet"))
        XCTAssertTrue(gallerySource.contains("plant-detail-photo-gallery-card"))
        XCTAssertTrue(gallerySource.contains("PlantPhotoDetailSheet"))
        XCTAssertTrue(gallerySource.contains("plant-detail-photo-detail-sheet"))
        XCTAssertTrue(gallerySource.contains("struct PlantDetailDecodedImageTile"))
        XCTAssertTrue(gallerySource.contains("AttachmentImageDecoder.decode"))
        XCTAssertTrue(featureHubSource.contains("enum PlantFeatureDestination"))
        XCTAssertTrue(featureHubSource.contains("struct PlantAllFeaturesSheet"))
        XCTAssertTrue(featureHubSource.contains("FeatureHubScaffold"))
        XCTAssertTrue(featureHubSource.contains("FeatureHubHeader"))
        XCTAssertTrue(featureHubSource.contains("FeatureHubMetricStrip"))
        XCTAssertTrue(featureHubSource.contains("FeatureHubSectionActionView"))
        XCTAssertTrue(featureHubSource.contains("plant-detail-all-features-sheet"))
        XCTAssertTrue(featureHubSource.contains("PlantHubFocusAction"))
        XCTAssertTrue(featureHubSource.contains("focusActionBanner"))
        XCTAssertTrue(featureHubSource.contains("focusAction"))
        XCTAssertTrue(featureHubSource.contains("nextDueTask"))
        XCTAssertTrue(featureHubSource.contains("destination(for: nextDueTask)"))
        XCTAssertTrue(featureHubSource.contains("plant-detail-feature-focus-\\(action.id)"))
        XCTAssertTrue(featureHubSource.contains("id: \"due-care\""))
        XCTAssertTrue(featureHubSource.contains("id: \"health-review\""))
        XCTAssertTrue(featureHubSource.contains("id: \"safety\""))
        XCTAssertTrue(featureHubSource.contains("id: \"profile\""))
        XCTAssertTrue(featureHubSource.contains("id: \"photos\""))
        XCTAssertTrue(featureHubSource.contains("id: \"first-log\""))
        XCTAssertTrue(featureHubSource.contains("case water"))
        XCTAssertTrue(featureHubSource.contains("case fertilize"))
        XCTAssertTrue(featureHubSource.contains("case pestCheck"))
        XCTAssertTrue(featureHubSource.contains("case leafCleaning"))
        XCTAssertTrue(featureHubSource.contains("case carePlan"))
        XCTAssertTrue(featureHubSource.contains("case calendar"))
        XCTAssertTrue(featureHubSource.contains("id: \"calendar\""))
        XCTAssertTrue(featureHubSource.contains("title: l.tr(zh: \"护理日历\""))
        XCTAssertTrue(featureHubSource.contains("计划会同步到日历和本地提醒"))
        XCTAssertTrue(featureHubSource.contains("destination: .calendar"))
        XCTAssertTrue(featureHubSource.contains("case reminders"))
        XCTAssertTrue(featureHubSource.contains("id: \"reminders\""))
        XCTAssertTrue(featureHubSource.contains("plant.remindersEnabled"))
        XCTAssertTrue(featureHubSource.contains("case healthReview"))
        XCTAssertTrue(featureHubSource.contains("id: \"healthReview\""))
        XCTAssertTrue(featureHubSource.contains("healthReviewSignalCount"))
        XCTAssertTrue(featureHubSource.contains("recentHealthReviewCount"))
        XCTAssertTrue(featureHubSource.contains("case photos"))
        XCTAssertTrue(featureHubSource.contains("case timeline"))
        XCTAssertTrue(featureHubSource.contains("case catalog"))
        XCTAssertTrue(featureHubSource.contains("case safety"))
        XCTAssertTrue(careLogSheetSource.contains("struct PlantCareLogSheet"))
        XCTAssertTrue(careLogSheetSource.contains("plant-care-log-sheet"))
        XCTAssertTrue(careLogSheetSource.contains("PlantCareLogContextItem"))
        XCTAssertTrue(careLogSheetSource.contains("PlantCareLogImpactItem"))
        XCTAssertTrue(careLogSheetSource.contains("PlantCareLogNoteSuggestion"))
        XCTAssertTrue(careLogSheetSource.contains("checkInContextCard"))
        XCTAssertTrue(careLogSheetSource.contains("plant-care-log-context"))
        XCTAssertTrue(careLogSheetSource.contains("contextMetric(_ item: PlantCareLogContextItem)"))
        XCTAssertTrue(careLogSheetSource.contains("plant-care-log-context-\\(item.id)"))
        XCTAssertTrue(careLogSheetSource.contains("saveImpactPreview"))
        XCTAssertTrue(careLogSheetSource.contains("plant-care-log-save-impact"))
        XCTAssertTrue(careLogSheetSource.contains("saveImpactItems"))
        XCTAssertTrue(careLogSheetSource.contains("saveImpactRow(_ item: PlantCareLogImpactItem)"))
        XCTAssertTrue(careLogSheetSource.contains("plant-care-log-impact-\\(item.id)"))
        XCTAssertTrue(careLogSheetSource.contains("careLogImpactDetail"))
        XCTAssertTrue(careLogSheetSource.contains("plant-care-log-type-\\(type.rawValue)"))
        XCTAssertTrue(careLogSheetSource.contains("plant-care-log-health-\\(status.rawValue)"))
        XCTAssertTrue(careLogSheetSource.contains("suggestedNotesSection"))
        XCTAssertTrue(careLogSheetSource.contains("plant-care-log-suggested-notes"))
        XCTAssertTrue(careLogSheetSource.contains("suggestedNotes"))
        XCTAssertTrue(careLogSheetSource.contains("appendSuggestedNote(_ text: String)"))
        XCTAssertTrue(careLogSheetSource.contains("plant-care-log-note-suggestion-\\(suggestion.id)"))
        XCTAssertTrue(careLogSheetSource.contains("plant-care-log-note"))
        XCTAssertTrue(careLogSheetSource.contains("plant-care-log-save"))
        XCTAssertTrue(careLogSheetSource.contains("GoDraftTextEditor"))
        XCTAssertTrue(careLogSheetSource.contains("PlantHealthStatus.allCases"))
        XCTAssertTrue(careLogSheetSource.contains("careTypeHint"))
        XCTAssertTrue(careLogSheetSource.contains("import PhotosUI"))
        XCTAssertTrue(careLogSheetSource.contains("@State private var selectedPhotoItem"))
        XCTAssertTrue(careLogSheetSource.contains("@State private var selectedPhotoData"))
        XCTAssertTrue(careLogSheetSource.contains("PhotosPicker(selection: $selectedPhotoItem, matching: .images)"))
        XCTAssertTrue(careLogSheetSource.contains("plant-care-log-photo-picker"))
        XCTAssertTrue(careLogSheetSource.contains("plant-care-log-photo-preview"))
        XCTAssertTrue(careLogSheetSource.contains("plant-care-log-photo-replace"))
        XCTAssertTrue(careLogSheetSource.contains("plant-care-log-photo-remove"))
        XCTAssertTrue(careLogSheetSource.contains("selectedCareType = .photo"))
        XCTAssertTrue(careLogSheetSource.contains("onSave(selectedCareType, trimmedNote"))
        XCTAssertTrue(careLogSheetSource.contains("selectedHealthStatus, selectedPhotoData"))
        XCTAssertFalse(careLogSheetSource.contains("Text(\"🌱\")"))
    }

    func testPlantCareCalendarOpensFilteredCalendarRoute() throws {
        let rootURL = repositoryRootURL()
        let detailSource = try source("Ohana/Features/Plants/Views/PlantDetailView.swift", rootURL: rootURL)
        let detailContainerSource = try source("Ohana/Features/Plants/PlantDetailDataContainer.swift", rootURL: rootURL)
        let plantRouteSource = try source("Ohana/Features/Plants/PlantRouteContainer.swift", rootURL: rootURL)
        let appRouteSource = try source("Ohana/App/RouteContainers/AppRouteDestinationContainers.swift", rootURL: rootURL)
        let contentSource = try source("Ohana/App/ContentView.swift", rootURL: rootURL)
        let calendarSource = try source("Ohana/Features/Calendar/Views/CalendarView.swift", rootURL: rootURL)
        let calendarContentSource = try source(
            "Ohana/Features/Calendar/Views/CalendarView+Content.swift",
            rootURL: rootURL
        )
        let calendarSupportSource = try source(
            "Ohana/Features/Calendar/Views/CalendarViewSupport.swift",
            rootURL: rootURL
        )

        XCTAssertTrue(detailSource.contains("let onOpenCalendar: (UUID) -> Void"))
        XCTAssertTrue(detailSource.contains("case .calendar"))
        XCTAssertTrue(detailSource.contains("showingAllFeaturesHub = false"))
        XCTAssertTrue(detailSource.contains("onOpenCalendar(plant.id)"))
        XCTAssertTrue(detailContainerSource.contains("onOpenCalendar: @escaping (UUID) -> Void = { _ in }"))
        XCTAssertTrue(detailContainerSource.contains("onOpenCalendar: onOpenCalendar"))
        XCTAssertTrue(plantRouteSource.contains("let onOpenCalendar: (UUID) -> Void"))
        XCTAssertTrue(plantRouteSource.contains("PlantDetailView("))
        XCTAssertTrue(plantRouteSource.contains("onOpenCalendar: onOpenCalendar"))
        XCTAssertTrue(appRouteSource.contains("let onPresentCalendar: ((String?) -> Void)?"))
        XCTAssertTrue(appRouteSource.contains("onPresentCalendar?(plantId.uuidString)"))
        XCTAssertTrue(contentSource.contains("onPresentCalendar: { entityID in"))
        XCTAssertTrue(contentSource.contains("appRoutes.presentCalendar(entityID: entityID)"))
        XCTAssertTrue(calendarSupportSource.contains("var plantId: String"))
        XCTAssertTrue(calendarSupportSource.contains("var selectedPlantId: String?"))
        XCTAssertTrue(calendarSupportSource.contains("static func plant(_ id: String)"))
        XCTAssertTrue(calendarSupportSource.contains("let plants: [Plant]"))
        XCTAssertTrue(calendarSupportSource.contains("calendar-filter-plant-\\(plant.name)"))
        XCTAssertTrue(calendarSupportSource.contains("onSelect(.plant(plant.id.uuidString))"))
        XCTAssertTrue(calendarSource.contains("@AppStorage(\"calendar_filterPlantId\")"))
        XCTAssertTrue(calendarSource.contains("preselectedEntityIsPlant(preselectedPetId) ? .plant(preselectedPetId)"))
        XCTAssertTrue(calendarSource.contains("var effectivePlantFilterId: String?"))
        XCTAssertTrue(calendarSource.contains("eventIsRelatedToPlant($0, plantId: plantId)"))
        XCTAssertTrue(calendarSource.contains("func preselectedEntityIsPlant(_ entityId: String) -> Bool"))
        XCTAssertTrue(calendarSource.contains("func eventIsRelatedToPlant(_ event: Event, plantId: String) -> Bool"))
        XCTAssertTrue(calendarContentSource.contains("plants: plants"))
        XCTAssertTrue(calendarContentSource.contains(".onChange(of: calendarFilterPlantId)"))
        XCTAssertTrue(calendarContentSource.contains("calendarFilterPlantId = selection.plantId"))
    }

    func testPlantCareLogHealthStatusFlowsThroughCommandExecutors() throws {
        let rootURL = repositoryRootURL()
        let homeCommandSource = try source("Ohana/Features/Home/HomeCommandExecutor.swift", rootURL: rootURL)
        let memberCommandSource = try source("Ohana/Features/Members/MemberInteractionCommands.swift", rootURL: rootURL)

        XCTAssertTrue(homeCommandSource.contains("healthStatus: PlantHealthStatus? = nil"))
        XCTAssertTrue(homeCommandSource.contains("photoData: Data? = nil"))
        XCTAssertTrue(homeCommandSource.contains("photoData: photoData"))
        XCTAssertTrue(homeCommandSource.contains("healthStatus: healthStatus"))
        XCTAssertTrue(memberCommandSource.contains("healthStatus: PlantHealthStatus? = nil"))
        XCTAssertTrue(memberCommandSource.contains("photoData: photoData"))
        XCTAssertTrue(memberCommandSource.contains("healthStatus: healthStatus"))
    }

    func testPlantEditSheetShowsProfileOverviewBeforeLongForm() throws {
        let rootURL = repositoryRootURL()
        let editSource = try source("Ohana/Features/Plants/Views/PlantDetailEditSheet.swift", rootURL: rootURL)

        XCTAssertTrue(editSource.contains("editProfileOverview"))
        XCTAssertTrue(editSource.contains("plant-edit-profile-overview"))
        XCTAssertTrue(editSource.contains("profileReadinessItems"))
        XCTAssertTrue(editSource.contains("profileCompletionPercent"))
        XCTAssertTrue(editSource.contains("draftCareSummary"))
        XCTAssertTrue(editSource.contains("draftEnvironmentSummary"))
        XCTAssertTrue(editSource.contains("draftSafetySummary"))
        XCTAssertTrue(editSource.contains("editOverviewFact"))
        XCTAssertTrue(editSource.contains("PlantEditFocusSection"))
        XCTAssertTrue(editSource.contains("@State private var selectedEditFocus: PlantEditFocusSection = .all"))
        XCTAssertTrue(editSource.contains("editFocusSummary"))
        XCTAssertTrue(editSource.contains("editFocusSwitcher"))
        XCTAssertTrue(editSource.contains("plant-edit-focus-switcher"))
        XCTAssertTrue(editSource.contains("editFocusButton(_ section: PlantEditFocusSection)"))
        XCTAssertTrue(editSource.contains("plant-edit-focus-\\(section.rawValue)"))
        XCTAssertTrue(editSource.contains("editFocusTint(for section: PlantEditFocusSection)"))
        XCTAssertTrue(editSource.contains("editFocusStatus(for section: PlantEditFocusSection)"))
        XCTAssertTrue(editSource.contains("focusedEditSections"))
        XCTAssertTrue(editSource.contains("case .all:"))
        XCTAssertTrue(editSource.contains("case .identity:"))
        XCTAssertTrue(editSource.contains("case .care:"))
        XCTAssertTrue(editSource.contains("case .environment:"))
        XCTAssertTrue(editSource.contains("case .potting:"))
        XCTAssertTrue(editSource.contains("case .growth:"))
        XCTAssertTrue(editSource.contains("case .safety:"))
        XCTAssertTrue(editSource.contains("case .notes:"))
        XCTAssertTrue(editSource.contains("withAnimation(GoMotion.selection)"))
        XCTAssertFalse(editSource.contains(".textFieldStyle(.roundedBorder)"))
    }

    private func repositoryRootURL() -> URL {
        URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
    }

    private func source(_ path: String, rootURL: URL) throws -> String {
        try String(contentsOf: rootURL.appendingPathComponent(path), encoding: .utf8)
    }
}
